src/host.rs
src/host_context.rs
src/lib.rs

Implements a uniform host-assisted conversion interface both for ValTypes and those which need a little more help.

sketch uniform conversion with host assistance

---

Cargo.toml
src/host.rs
src/host_context.rs
src/host_context/debug.rs

Many incomplete bits but the basic recursive conversion into HostObject seems to work and produce objects that deep-compare correctly.

sketch ScVal/ScObject to Val/HostObject conversion

---

src/host_context.rs

More todo!()-laden code sketching the reverse conversion direction for host values returning to XDR

Sketch from_host_{val,obj}

---

Cargo.toml
src/host_context.rs

update to follow xdr definitions

remove primitive wrappers

---

src/host_context.rs
src/status.rs

just filling in some missing branches the obvious way

implement a few todos

---

src/host.rs

Rename `HostConvertible` fns:
- `0i64.val_from(host)` => `0i64.into_val(host)`
- `i64::try_val_into(v, host)` => `i64::try_from_val(v, host)`
When I was updating a contract in the SDK to use the `HostConvertible` trait, I found the current naming unintuitive because it doesn't follow any of the common `as_`, `to_`, `into_`, `try_into`, `from_`, `try_from` function prefix conventions. It took me a bit to dig into the fns and their internals to figure out what I needed to use and how. I think if we name these functions similar to the `into_` and `try_from` patterns that already exist, these fns will be easier to discover.
Initially I considered `to_val` for the first function, but referring to the following naming conventions I believe `into` is more accurate since the cost is variable …

Rename HostConvertible fns

---

src/bitset.rs
src/host_context.rs
src/host_context/host_object.rs
src/status.rs
src/symbol.rs
src/val.rs

Mostly sketching the XDR host object types since they implement Ord now.

Misc todo!() finishing

---

.github/workflows/rust.yml

Add more cases to handle "vm" feature in common

---

stellar-contract-env-host/src/host_object.rs
stellar-contract-env-host/src/lib.rs
stellar-contract-env-host/src/vm.rs

This just tidies up the interface for core.

Better public vm invoke

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-common/src/unimplemented_env.rs
stellar-contract-env-guest/src/guest.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/weak_host.rs

Add EnvBase::deep_clone, implement on Host.

---

stellar-contract-env-host/src/test.rs

Add unit test cases for numbers (u32, i32, u64, i64)
[TODO or N/A]

Add tests cases for numbers in host

---

stellar-contract-env-common/src/env_val.rs
stellar-contract-env-common/src/raw_val.rs
stellar-contract-env-common/src/symbol.rs
stellar-contract-env-common/src/tagged_val.rs

Add as/to_raw() to TaggedVal, and fix up some other minor things like unnecessary refs and unnecessary closures.
The as/to_raw() is more convenient than as_ref().clone() that has showed up a bit.
[TODO or N/A]

Fix up a few minor things

---

stellar-contract-env-common/src/env_val.rs
stellar-contract-env-common/src/raw_val.rs
stellar-contract-env-host/src/host.rs

Followup from today's protocol meeting.

Change function names from "positive i64" back to "u63"

---

stellar-contract-env-common/src/symbol.rs

Impl From<String>/ToString for Symbol.
Convenience functions for use in tests, and in host code.
[TODO or N/A]

Impl From<String>/ToString for Symbol

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs

Add host functions signatures promised in [CAP-51](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0051.md). No impl.  
Implementation will be done later.

Add hostfns signatures promised in CAP-51

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs

Update map iterator hostfn signatures
- map_prev_key
- map_next_key
- map_min_key
- map_max_key
No impl. 
[TODO or N/A]

Update map iterator hostfn signatures

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs

- Update hostfn signatures to be consistent with CAP-51.
- Implement vec_slice and updates tests.
[TODO or N/A]

Up-to-date with CAP-51; impl vec_slice

---

Cargo.lock
stellar-contract-env-common/Cargo.toml
stellar-contract-env-common/src/symbol.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/storage.rs
stellar-contract-env-host/src/test.rs

Adds `Host::invoke_function` which is the entry-point for CAP-52. Also updates storage to support any ledger entry type.
Required to implement CAP-52 in stellar/stellar-core.
N/A

Add functionality for CAP-52

---

Cargo.lock
stellar-contract-env-common/src/env.rs
stellar-contract-env-host/Cargo.toml
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs

Implements the `compute_hash_sha256` and `verify_sig_ed25519` host functions.

Crypto host functions

---

stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs

Add impl of map_put, map_has, map_get.
Need it for the SDK for user-defined type encoding as maps.
[TODO or N/A]

Add impl of map_put, map_has, map_get

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-common/src/raw_val.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/host_object.rs

Implement `map` and `binary` host functions

---

stellar-contract-env-common/src/symbol.rs
stellar-contract-env-host/src/host.rs

Remove a few warnings and unnecessary conversions.
Clean up.
[TODO or N/A]

Remove a few warnings and unnecessary conversions

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs

Solves https://github.com/stellar/rs-stellar-contract-env/issues/167
[TODO or N/A]

Change serialize/deserialize fns to operation on Val

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs

Related to https://github.com/stellar/stellar-protocol/issues/1259.

Update create contract function names

---

stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs

Resolves https://github.com/stellar/rs-stellar-contract-env/issues/192

Fix create contract separator

---

Cargo.lock
stellar-contract-env-common/src/env.rs
stellar-contract-env-host/Cargo.toml
stellar-contract-env-host/src/budget.rs
stellar-contract-env-host/src/events.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/lib.rs

This is just some preliminary work to have an event buffer and allow writing both protocol-level (TBD) and diagnostic / debug-log (currently useful!) entries to it.

Add some infrastructure for event logging, including debug events.

---

Cargo.lock
stellar-contract-env-common/Cargo.toml
stellar-contract-env-host/Cargo.toml
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs

Allows the user to enable serde support

Serde feature

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-common/src/option.rs
stellar-contract-env-common/src/tuple.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs
stellar-contract-env-host/tests/integration.rs

Resolves https://github.com/stellar/rs-stellar-contract-env/issues/196
[TODO or N/A]

Change vec_new to take in an optional capacity parameter

---

stellar-contract-env-host/src/budget.rs

Fix variant list of CostTypeBudget and make pub.
The CLI will use the variant list.
For https://github.com/stellar/stellar-contract-cli/issues/25
Related to 
[TODO or N/A]

Fix variant list of CostTypeBudget and make pub

---

Cargo.lock
stellar-contract-env-host/Cargo.toml

Remove dependency `num-rational`.
It is no longer used.
[TODO or N/A]

Remove unused dependency num-rational

---

stellar-contract-env-common/src/raw_val.rs

Add conversions for borrowed types.
It's common to provide these allongside the not-borrows.
[TODO or N/A]

Add conversions for borrowed types

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs

Add host functions and fix bugs needed for example liquidity pool contract. Related to https://github.com/stellar/stellar-protocol/pull/1270.
A step toward publishing an example liquidity pool contract.
None

Liquidity pool contract support

---

stellar-contract-env-common/src/symbol.rs

Added TryFrom Symbol/ScVal.
Make https://github.com/stellar/rs-stellar-contract-sdk/pull/316 work.
This is eating conversion errors, in the interest of getting something working as quickly as possible.

Add conversions Symbol <-> ScVal

---

stellar-contract-env-common/src/bitset.rs
stellar-contract-env-common/src/raw_val.rs

For https://github.com/stellar/rs-stellar-contract-sdk/issues/328

Change BitSet to struct

---

Cargo.lock
Cargo.toml
stellar-contract-env-panic-handler-wasm32-unreachable/Cargo.toml
stellar-contract-env-panic-handler-wasm32-unreachable/src/lib.rs

Follow up to https://github.com/stellar/rs-stellar-contract-sdk/pull/344
For https://github.com/stellar/jump-cannon-deliverables/issues/9

Remove panic handler crate

---

stellar-contract-env-common/src/bitset.rs
stellar-contract-env-common/src/checked_env.rs
stellar-contract-env-common/src/convert.rs
stellar-contract-env-common/src/env.rs
stellar-contract-env-common/src/env_val.rs
stellar-contract-env-common/src/lib.rs
stellar-contract-env-common/src/meta.rs
stellar-contract-env-common/src/object.rs
stellar-contract-env-common/src/raw_val.rs
stellar-contract-env-common/src/static.rs
stellar-contract-env-common/src/status.rs
stellar-contract-env-common/src/symbol.rs
stellar-contract-env-common/src/unimplemented_env.rs
stellar-contract-env-common/src/val.rs
stellar-contract-env-common/src/val_wrapper.rs
stellar-contract-env-host/src/events.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/host/err_helper.rs

First round of API docs on contract-env-common, will add more tomorrow.

Some API docs on contract-common

---

LICENSE

Add license blocks to all files and license files to the root.

license everything

---

soroban-env-common/src/checked_env.rs
soroban-env-common/src/env.rs
soroban-env-common/src/meta.rs
soroban-env-common/src/raw_val.rs
soroban-env-host/Cargo.toml
soroban-env-host/src/events.rs
soroban-env-host/src/host/err_helper.rs
soroban-env-host/src/lib.rs
soroban-env-host/src/storage.rs
soroban-env-host/src/vm.rs

Add some host API docs

---

soroban-env-guest/src/guest.rs
soroban-env-guest/src/lib.rs
soroban-env-host/src/lib.rs

Add minimal docs to guest crate

---

soroban-env-common/Cargo.toml
soroban-env-guest/Cargo.toml
soroban-env-host/Cargo.toml
soroban-env-macros/Cargo.toml

bump to 0.0.3

---

Cargo.lock
soroban-env-host/src/budget.rs

So that we don't block testing and running examples. 
https://github.com/stellar/rs-soroban-sdk/issues/382
[TODO or N/A]

Set default budget limits to unlimited

---

soroban-env-host/src/vm.rs

Fix charge_mem to charge CostType::WasmMemAlloc, close #295

---

soroban-env-host/src/host.rs
soroban-env-host/src/host/conversion.rs
soroban-env-host/src/host/data_helper.rs

More clean-ups. 
Preparing for metering changes. 
[TODO or N/A]

More clean-up on contract data and storage-related

---

soroban-env-host/src/host.rs
soroban-env-host/src/ledger_info.rs
soroban-env-host/src/lib.rs

This will allow the sdk to construct a `LedgerInfo` to pass to `Host::set_ledger_info`.

Expose LedgerInfo

---

soroban-test-wasms/wasm-workspace/Cargo.toml

Add some more comments as a followup to https://github.com/stellar/rs-soroban-env/pull/354

More commentary on when and how to regenerate WASM tests

---

Cargo.lock
Cargo.toml

What it says on the label. Pulling in LedgerCloseMetaV2

Update to rs-stellar-xdr@925dcea0

---

Cargo.lock
Cargo.toml
soroban-env-host/src/host.rs
soroban-env-host/src/native_contract/token/public_types.rs

- Fix https://github.com/stellar/rs-soroban-env/pull/394#discussion_r959006267
- Add `register_test_contract_token`
- Bump stellar-xdr to pick up https://github.com/stellar/rs-stellar-xdr/pull/149
Clean up.
N/A

Native token cleanup

---

.github/workflows/bump-version.yml
.github/workflows/rust.yml
Makefile

Copy @leighmcculloch's new release automation from https://github.com/stellar/bytes-lit

Release automation

---

Cargo.lock
Cargo.toml
soroban-env-common/Cargo.toml
soroban-env-macros/Cargo.toml

Bump the stellar-xdr dep to 0.0.2

Bump stellar-xdr dep to 0.0.2

---

.github/workflows/rust.yml

Reorder cargo install options to match other repos.
Consistency with other repos that do the same thing.

Reorder cargo install options to match other repos

---

.github/workflows/rust.yml

Separate the publish workflows and use new versions
.

Separate the publish workflows and use new versions

---

.github/workflows/publish.yml
.github/workflows/rust.yml

Move publish workflow to separate workflow.

Move publish workflow to separate workflow

---

soroban-env-host/src/host.rs
soroban-env-host/src/test/invocation.rs

Add invocation error debug event to `Env::call` like `Env::try_call`.
A developer will choose call or try_call based on how they want to handle an error. In both cases diagnostics about the error are useful, and it is confusing that the diagnostic events are inconsistent. The fact the debug events are different implies something different has taken place inside the called contract, when the calls are the same.

Add invocation error debug event to call like try_call

---

soroban-env-common/src/symbol.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/260 
[TODO or N/A]

Use `ConversionError` for `Symbol`<->`ScVal`

---

Cargo.lock
Cargo.toml
soroban-env-host/src/host.rs
soroban-env-host/src/host/conversion.rs
soroban-env-host/src/host_object.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/157
[TODO or N/A]

Remove `Hash` and `PublicKey` from objects

---

soroban-env-common/src/tuple.rs
soroban-env-host/src/test.rs
soroban-env-host/src/test/tuple.rs

Add tuple to [RawVal; N] conversions.
These conversions can be convenient.

Add tuple to [RawVal; N] conversions

---

Cargo.lock
soroban-env-host/Cargo.toml
soroban-env-host/benches/calibrate_host_ops.rs
soroban-env-host/src/budget.rs
soroban-env-host/src/host.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/296 by putting in some cost parameters and budget.
[TODO or N/A]

Add comments to each `CostType`; add very crude, untested model parameters

---

soroban-env-common/src/raw_val.rs

Add missing TryIntoVal<_, RawVal> for RawVal conversion

Add missing TryIntoVal<_, RawVal> for RawVal conversion

---

soroban-env-host/src/native_contract/token/cryptography.rs

Remove `panic!`s from builtin contract.
Host shouldn't panic
N/A

Remove `panic!`s from builtin contract.

---

soroban-env-host/src/host.rs

Fix sponsorship handling in `transfer_account_balance`.
The fix is according to the Core implementation: https://github.com/stellar/stellar-core/blob/master/src/transactions/TransactionUtils.cpp#L835
N/A

Fix sponsorship handling in `transfer_account_balance`.

---

soroban-env-host/src/budget.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/conversion.rs
soroban-env-host/src/host/data_helper.rs
soroban-env-host/src/host/metered_clone.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/479 for `AccountId`.
Plus `ContractCode`. 
Along with some minor fixes.
[TODO or N/A]

Add metering for `AccountId` and `ContractCode`

---

soroban-env-host/src/native_contract/token/contract.rs

Check all built-in token ops to have non-negative amounts.
None of the token ops make sense with negative amount.
N/A

Check all built-in token ops to have non-negative amounts.

---

soroban-env-host/src/native_contract/token/contract.rs

Use import and export instead of to_smart and to_classic

---

Cargo.lock
Cargo.toml
soroban-env-common/src/symbol.rs
soroban-env-host/src/events.rs

Update stellar-xdr and get BytesM/StringM types.
See stellar/xdrgen#143
Close https://github.com/stellar/xdrgen/issues/125 
Close https://github.com/stellar/xdrgen/issues/119 
Close https://github.com/stellar/xdrgen/issues/118

Update stellar-xdr and get BytesM/StringM

---

soroban-env-host/src/native_contract/token/contract.rs

Remove reference to `create_token_from_asset`, which was removed.

fix comment

---

soroban-env-host/src/native_contract/token/contract.rs

Remove unnecessary i128 clone.
[TODO or N/A]

Remove unnecessary i128 clone

---

soroban-env-host/src/host.rs

When configured for testing, in `Host::call_n`, call the new `call_with_suppressed_panic_hook` to catch panics. `call_with_suppressed_panic_hook`:
- performs a one-time override of the global panic hook
- wraps the original panic hook
- tracks a thread local contract-call recursion count
- when the recursion count is zero, forwards to the original panic hook, maintaining the original hook's behavior
- when the recursion count is non-zero, does nothing
The `call_with_suppressed_panic_hook` function is extracted out of the `call_n` function for easier reading, and gets its own module to avoid many extra `cfg`s.
The existing code is written to suppress the default printing of the global panic hooks when calling contracts in testing mode; later performing a single panic once all contract …

Fix override of panic hook during cross-contract testing

---

Cargo.lock
Cargo.toml
soroban-env-common/src/raw_val.rs
soroban-env-common/src/status.rs
soroban-env-host/src/auth.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/652

Use auth specific errors

---

Cargo.lock
Cargo.toml
soroban-env-host/src/auth.rs
soroban-env-host/src/native_contract/testutils.rs

Fix missing nonce in the payload
Bug fix
N/A

Nonce bug fix

---

soroban-env-common/src/num.rs
soroban-env-common/src/object.rs
soroban-env-common/src/raw_val.rs
soroban-env-common/src/wrapper_macros.rs
soroban-env-host/src/events/internal.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/conversion.rs
soroban-env-host/src/host/data_helper.rs
soroban-env-host/src/host/metered_xdr.rs
soroban-env-host/src/host/validity.rs
soroban-env-host/src/native_contract/token/balance.rs
soroban-env-host/src/test.rs
soroban-env-host/src/test/lifecycle.rs
soroban-env-host/src/test/map.rs
soroban-env-host/src/test/num.rs
soroban-env-host/src/test/str.rs
soroban-env-host/src/test/token.rs
soroban-env-host/src/test/util.rs

- Moved some definitions (RawVal, ScValObject) up a few lines for easier mental load
- Bug fix for small.signed number conversion
- Fixed a couple of tests
- Some small changes/improvements
[TODO or N/A]

Small changes and fixes

---

soroban-env-host/src/host.rs

Make all the functions starting with "__" reserved.
This allows adding special functions like `__check_auth` in the future protocol versions  without risking breaking the existing contracts.
N/A

Make all the functions starting with "__" reserved.

---

Cargo.lock
Cargo.toml
soroban-env-host/src/host/declared_size.rs

Bump env XDR version
Keeping up with XDR changes
N/A

Bump env XDR

---

Cargo.lock
Cargo.toml

Bump xdr version

---

Cargo.lock
soroban-env-common/Cargo.toml
soroban-env-macros/Cargo.toml
soroban-native-sdk-macros/Cargo.toml
soroban-native-sdk-macros/src/derive_fn.rs
soroban-native-sdk-macros/src/lib.rs

Trying to kill off dependencies on syn1

Move to syn2

---

Cargo.lock
Cargo.toml
deny.toml
soroban-env-host/Cargo.toml

More syn-1 dependency trimming

Bump dep on bytes-lit to 0.0.5 to trim dep on syn 1

---

soroban-env-host/src/native_contract/token/balance.rs
soroban-env-host/src/native_contract/token/contract.rs
soroban-env-host/src/test/token.rs

Enforce AUTH_REVOCABLE on contract balances to match classic and SAC account balance behavior.

Enforce AUTH_REVOCABLE on contract balances

---

soroban-env-host/src/expiration_ledger_bumps.rs
soroban-env-host/src/host.rs
soroban-env-host/src/lib.rs
soroban-env-host/src/test/complex.rs

Implement contract expiration bumps

---

soroban-env-host/benches/common/cost_types/guard_frame.rs
soroban-env-host/benches/common/cost_types/num_ops.rs
soroban-env-host/src/host/frame.rs
soroban-env-host/src/vm.rs

Broken due to recent changes: instance storage, [IU]256
[TODO or N/A]

Fix calibration tests

---

Cargo.lock
Cargo.toml

Bump wasmi version

---

soroban-env-host/src/fees.rs
soroban-env-host/tests/fees.rs

Add a function to compute the rent fee.
Also refactor the resource fee computation faction to return non-refundable and refundable fees separately.
Support for the rent fee computation.
N/A

Add a function to compute the rent fee.

---

soroban-env-host/src/auth.rs

Use host.err to create a debug event.

Use host.err for auth error

---

soroban-env-host/src/test/lifecycle.rs

Add a smoke test for recording auth for create contract host fn.
Increase test coverage
N/A

Add a smoke test for recording auth for create contract host fn.

---

soroban-env-host/src/native_contract.rs
soroban-env-host/src/native_contract/storage_utils.rs
soroban-env-host/src/native_contract/token/allowance.rs
soroban-env-host/src/native_contract/token/balance.rs

Stop treating storage errors as missing entries

---

soroban-env-common/src/symbol.rs

While working on refreshing CAPs, I realized I had half-forgotten which byte-alignment we wound up storing Symbol in. This just adds some specific test vectors and a comment explaining the type a bit more. No functional change.

add some comments and tests to env-common/symbol.rs

---

soroban-env-host/src/auth.rs

Fix incorrect argument name (allow/disable semantics confused)
Improve readability
N/A

Fix incorrect argument name

---

soroban-env-host/src/fees.rs
soroban-env-host/tests/fees.rs

Reduce the expiration entry write size.
It erroneously took key size into account.
N/A

Reduce the expiration entry write size.

---

.github/workflows/rust.yml

Enable build workflow for pull request merge queue merge groups.
Same as https://github.com/stellar/rs-soroban-sdk/pull/1072.

Enable build workflow for merge groups

---

.github/workflows/rust.yml

Add git rev dep check to ci
Close stellar/actions#55

Add git rev dep check to ci

---

soroban-env-common/src/val.rs

This is just a slight fix following https://github.com/stellar/rs-soroban-env/pull/1012 to avoid the duplicate logic @brson noted in that PR.

Factor Tag::is_object to let Val::is_object delegate to it

---

soroban-env-host/src/budget.rs
soroban-env-host/src/test/budget_metering.rs

Updated the comment, reduced the memory a bit, and made the constants private (they shouldn't serve as a source of truth for the network config).
Documentation improevment
N/A

Small update for the default budget limits.

---

soroban-env-host/src/auth.rs
soroban-env-host/src/cost_runner/runner.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/crypto.rs
soroban-env-host/src/host/data_helper.rs
soroban-env-host/src/host/error.rs
soroban-env-host/src/host/lifecycle.rs
soroban-env-host/src/host/validity.rs

This round does not involve any significant functional changes, though some might be observable. It's mostly cleanup, code reorg (including a new file `lifecycle.rs`), a bit of refactoring and some making stuff private.

Host code review, minor cleanups and code reorganization

---

soroban-env-host/src/auth.rs
soroban-env-host/src/host/frame.rs

Replace `expect` call with error.

Remove panic

---

soroban-env-host/src/host/frame.rs

It's conceivable someone else might have pushed a frame besides `with_frame` so we should handle going _past_ the depth limit as well as just hitting it.
Also remove an assert which, if wrong, would panic.

Remove a panic and be more conservative about depth limit

---

soroban-env-host/src/test/auth.rs
soroban-env-host/src/test/stellar_asset_contract.rs

Improve auth test coverage a bit:
- Missing account/custom account entries
- Incorrect signature format
Improving test coverage (https://github.com/stellar/rs-soroban-env/issues/1169)
N/A

Improve auth test coverage a bit

---

soroban-env-host/src/test/lifecycle.rs
soroban-env-host/src/test/storage.rs

Write some of the tests mentioned in https://github.com/stellar/rs-soroban-env/issues/1159.

Storage tests

---

soroban-env-host/src/test/event.rs
soroban-env-host/src/test/invocation.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/916 and https://github.com/stellar/rs-soroban-env/issues/1167
By adding the following tests:
- Recording diagnostic events with `DEBUG` on and off do not affect metering
- Excessive contract events: large single-topic, large numbers of topics, large data, recording events in a loop will all fail
- Contract with failure with `DEBUG` on and off do not affect metering
[TODO or N/A]

More events and diagnostics testing

---

soroban-env-host/src/test/lifecycle.rs

Cover non-existent Wasm in test for updating Wasm.
Resolves https://github.com/stellar/rs-soroban-env/issues/1149
Improving test coverage.
N/A

Cover non-existent Wasm in test for updating Wasm.

---

soroban-env-common/src/error.rs
soroban-env-host/benches/common/cost_types/invoke.rs
soroban-env-host/benches/common/cost_types/wasm_insn_exec.rs
soroban-env-host/src/test/complex.rs
soroban-env-host/src/test/hostile.rs
soroban-env-host/src/test/metering_benchmark.rs
soroban-env-host/src/test/post_mvp.rs
soroban-env-host/src/test/util.rs
soroban-synth-wasm/src/expr.rs
soroban-synth-wasm/src/mod_emitter.rs
soroban-synth-wasm/src/test.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/896
[TODO or N/A]

Add wasm test for excessive initial memory and table size

---

Cargo.lock
cackle.toml
soroban-builtin-sdk-macros/Cargo.toml
soroban-env-common/Cargo.toml
soroban-env-host/Cargo.toml
soroban-env-macros/Cargo.toml
soroban-synth-wasm/Cargo.toml
soroban-synth-wasm/src/mod_emitter.rs

This just does one final dep update to env before we commit to final. Seems like there was nothing major.

Update deps, fix #1200

---

soroban-env-host/src/e2e_invoke.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/1216
[TODO or N/A]

Validated TTLentries

---

soroban-env-host/src/budget.rs
soroban-env-host/src/budget/dimension.rs
soroban-env-host/src/budget/model.rs
soroban-env-host/src/budget/util.rs

Not much here, just minor bits of cleanup and eliminating impossible panics for a bit of future-proofing.

Budget subsystem code review

---

Makefile
publish-dry-run.sh

Missed this in previous change.

Pass --locked to publish as well

---

soroban-env-host/observations/test__host__invalid_val.json
soroban-env-host/observations/test__map__scmap_duplicate.json
soroban-env-host/observations/test__map__scmap_invalid_element.json
soroban-env-host/observations/test__symbol__invalid_symbol_scval_to_val.json
soroban-env-host/src/test.rs
soroban-env-host/src/test/host.rs
soroban-env-host/src/test/invocation.rs
soroban-env-host/src/test/map.rs
soroban-env-host/src/test/symbol.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/1147

Conversion tests

---

soroban-builtin-sdk-macros/src/derive_type.rs
soroban-builtin-sdk-macros/src/lib.rs
soroban-env-host/src/builtin_contracts.rs
soroban-env-host/src/builtin_contracts/account_contract.rs
soroban-env-host/src/builtin_contracts/base_types.rs
soroban-env-host/src/builtin_contracts/common_types.rs
soroban-env-host/src/builtin_contracts/contract_error.rs
soroban-env-host/src/builtin_contracts/invoker_contract_auth.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/admin.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/allowance.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/asset_info.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/balance.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/contract.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/event.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/metadata.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/public_types.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/storage_types.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/test_stellar_asset_contract.rs
soroban-env-host/src/builtin_contracts/storage_utils.rs
soroban-env-host/src/host/data_helper.rs
soroban-env-host/src/test/auth.rs
soroban-env-host/src/test/hostile_opt.rs
soroban-env-host/src/test/stellar_asset_contract.rs

I still have 3 large-ish files in the SAC to look at but need to take a pause to switch tasks, and this is a good stopping point. There's nothing too serious in here, but a bit of churn:
- Removed a bunch of dead code
- Made a lot of stuff pub(crate) -- and had to change macro to deal with that
- Factored out some common patterns in balance.rs
- Merged-and-sorted imports
I'll post another of these once I have the rest of the SAC done

Initial SAC review 

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml

Take updates on recent releases of deps

Bump wasmi and xdr to release versions

---

soroban-env-host/src/builtin_contracts/account_contract.rs
soroban-env-host/src/builtin_contracts/invoker_contract_auth.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/contract.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/metadata.rs

Just the second and final part of SAC code review. Not much, just minor janitorial stuff.

SAC final code review

---

soroban-env-host/src/builtin_contracts/account_contract.rs

Improve error for missing signatures.
[TODO or N/A]

Improve error for missing signatures.

---

soroban-simulation/src/fees.rs
soroban-simulation/src/lib.rs

1. Backport https://github.com/stellar/soroban-tools/pull/1131
2. Make `ledger_storage` module public

soroban-simulate: Misc fixes

---

Cargo.lock
Cargo.toml

Bump wasmi to 0.31.1-soroban.20.0.1

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml

Bump XDR dependency for write fee in LCM.
This is necessary for the respective Core change.
N/A

Bump XDR dependency for write fee in LCM

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml

Bump XDR used by env to pick up env meta changes.
Picking up changes in https://github.com/stellar/stellar-xdr/pull/175
N/A

Bump XDR used by env

---

soroban-env-host/src/host.rs
soroban-env-host/src/host/data_helper.rs

To avoid code duplication. 
Previous [attempt](https://github.com/stellar/rs-soroban-env/pull/1368) broke some code observation so it had to be reverted. This PR fixes it. 
[TODO or N/A]

Refactor extend {code, instance} TTL

---

soroban-env-host/src/host/metered_xdr.rs

Reuse the `sha256_hash_from_bytes_raw` instead of reimplementing it in `metered_hash_xdr`
[TODO or N/A]

Reuse hash method in `metered_hash_xdr`

---

Cargo.lock
soroban-env-host/Cargo.toml

Pin deps to what is used in core.

Set dep versions to what is used in core

---

Cargo.lock
soroban-env-host/Cargo.toml

The stellar-xdr dev dependency wasn't updated in the previous PR. This PR updates it. 
[TODO or N/A]

Update dev xdr hash

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml

Picks up https://github.com/stellar/rs-stellar-xdr/pull/361 
[TODO or N/A]

Update xdr hash

---

Makefile
soroban-env-host/src/test/e2e_tests.rs
soroban-env-host/src/test/stellar_asset_contract.rs
soroban-env-host/src/testutils.rs

Add e2e test for custom account authorization.
The main purpose of the test is to make sure that the recording mode works correctly for custom accounts.
N/A

Add e2e test for custom account authorization.

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml

Bump to xdr 20.0.1

---

soroban-env-host/src/events/internal.rs
soroban-env-host/src/events/mod.rs
soroban-env-host/src/host.rs
soroban-env-macros/src/call_macro_with_all_host_functions.rs

Required for https://github.com/stellar/rs-soroban-sdk/pull/1265.

Expose method to pull just diagnostics

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml

Just carrying on the XDR-bump and minor-release train steps

Take XDR update and bump version to 21.1.0

---

soroban-env-host/Cargo.toml

curve25519 is also subject to the security advisory and needs to be bumped
[TODO or N/A]

Relex curve25519-dalek version

---

soroban-env-host/src/e2e_invoke.rs
soroban-env-host/src/host/comparison.rs
soroban-env-host/src/test/budget_metering.rs
soroban-env-host/src/test/bytes.rs
soroban-env-host/src/test/e2e_tests.rs
soroban-env-host/src/test/event.rs
soroban-env-host/src/test/lifecycle.rs
soroban-env-host/src/test/observe.rs
soroban-env-host/src/test/prng.rs
soroban-env-host/src/test/stellar_asset_contract.rs
soroban-env-host/src/test/storage.rs
soroban-env-host/src/testutils.rs
soroban-env-host/tests/fees.rs

clippy formatting fixes

---

soroban-env-common/src/symbol.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/812
Improved error message for Symbol validation error.
Error improvement
N/A

Improved error message for Symbol validation error.

---

Cargo.lock
Cargo.toml
deny.toml
soroban-env-host/Cargo.toml

Just update deps for p22
fix #1353 
fix #1313

Update dalek crates, k256, and wasmi for protocol 22

---

Cargo.lock
Cargo.toml

We want to release an rc version first.

Set version to 22.0.0-rc.1

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml
soroban-test-wasms/wasm-workspace/Cargo.toml

Set xdr version to 22.0.0-rc.1

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml

Update the main branch to v22.0.0

Bump env and xdr to v22.0.0

---

soroban-env-host/benches/common/cost_types/invoke.rs
soroban-env-host/benches/common/cost_types/wasm_insn_exec.rs

Fixes for benchmark build
Make it build again.
N/A

Fixes for benchmark build

---

Cargo.lock
Cargo.toml
cackle.toml
soroban-env-host/Cargo.toml

Bump XDR in env to pick up the most recent changes.
Keeping it up to date
N/A

Bump XDR in env to pick up the most recent changes.

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml

Bump XDR to pick the most recent p23 changes.
Keeping it up to date
N/A

Bump XDR to pick the most recent p23 changes

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml
soroban-simulation/src/test/network_config.rs

Bump XDR to pick up tx_max_in_memory_read_entries rename
Keeping XDR up to date
N/A

Bump XDR to pick up tx_max_in_memory_read_entries rename

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml

Update version to 23.0.0-rc.1.
This has to be done manually as the action doesn't allow for downgrades.
Protocol 23 release process
N/A

Update version to 23.0.0-rc.1

---

docs/GUEST_INTERFACE.md

[rendered](https://github.com/stellar/rs-soroban-env/blob/fa61bd5bb292b5779dc17580ffdb67901d27d2e7/docs/GUEST_INTERFACE.md)
This is an initial attempt at https://github.com/stellar/rs-soroban-env/issues/184 as well as a certain amount of https://github.com/stellar/rs-soroban-env/issues/706 
Probably neither should be entirely closed yet, since there's more to write, but it's a start.

Add guest interface doc

---

soroban-env-host/src/host.rs
soroban-env-host/src/host/conversion.rs
soroban-env-host/src/host/metered_map.rs

Add error message for converting non-sorted ScMaps to Val.
Fixes https://github.com/stellar/rs-soroban-env/issues/1510
N/A

Add error message for converting non-sorted ScMaps to Val.
