src/host_context.rs
src/host_context/host_object.rs
src/host_context/val_in_context.rs

Make more of the object-adding type directed, make the Rc invisible to users, move code around for organization, implement a host function (map_new).

Reorg, add HostObjectType, bury Rc<HostContextImpl>

---

src/val.rs

Make payload accessors public so they can be used from core.

Make payload functions public

---

Cargo.toml
src/host_context.rs

Update stellar-xdr to the latest commit. Update locations that used variable length arrays and opaques to use the `VecM` type.
Keep it up-to-date. Also, I'm starting work on the host interface, and I need the host and sdk libs to be using the same version of the XDR lib.
The VecM type has some traits and functions implemented like TryFrom from a few types (Vec, slice, arrays, etc), AsRef (for slices), and a few functions like `iter`, `as_vec`, `to_vec`. And I noticed that `()` is commonly used as an error type in this crate, so I've also added a From impl for converting the errors from the xdr lib into `()` so we can map automatically. 
Please let me know if there are other conveniences I should add, specifically for the VecM.

Update the xdr

---

src/host.rs
src/host_context.rs

Change `try_from_val` and associated fns and impls so that they do not require a mutable `Host`.
As far as we know the `Host` should not require changing during these states since these functions are purely reading out data.
N/A

Make Host immut when mut not needed

---

src/val.rs

Remove the `TryFrom` impls for `i64`<->`Val`.
These `TryFrom` impls look like footguns when using `Val` in the contract SDK. It's too easy to call `.try_from` for `Val` -> `i64` when the developer should really be calling `i64::try_from_val`. If we give the developer the choice we're encouraging a leak of the u63 concept into developer code.
As far as I can tell these `TryFrom` impls have no use in the host crate, and so I suspect they are just a holdover from the SDK.
I'm not sure if there's a future use for these. If there is a future use for these, is there a way to hide them from the SDK so that when the SDK imports and uses Val, it doesn't get them?

Remove TryFrom i64<->Val impls that can be footguns

---

src/host.rs
src/host_context.rs

Remove the convenience-only generic fns from the Host trait.
They prevent using the Host trait in dyn trait situations. As far as I can tell these functions on the Host trait only exist out of convenience but otherwise don't need to be part of the interface that the Host trait provides.
As a bonus of this change, any code doing these conversions will look the same rather than being one of the two different ways of doing conversions.
N/A

Remove convenience-only generic fns from Host trait

---

Cargo.toml

Include `stellar-xdr`'s `std` feature in the `host_context` feature, and disable stellar-xdr's default features.
We only want to import `stellar-xdr` with `std` if we're building for the `host_context`, because when we're building for the guest context, we are avoiding use of `std`.
N/A

Add stellar-xdr/std to host_context feature

---

stellar-contract-env-common/src/bitset.rs
stellar-contract-env-common/src/env.rs
stellar-contract-env-common/src/env_obj.rs
stellar-contract-env-common/src/env_val.rs
stellar-contract-env-common/src/lib.rs
stellar-contract-env-common/src/raw_obj.rs
stellar-contract-env-common/src/raw_val.rs
stellar-contract-env-common/src/status.rs
stellar-contract-env-common/src/symbol.rs
stellar-contract-env-guest/src/guest.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/host_object.rs
stellar-contract-env-host/src/lib.rs
stellar-contract-env-host/src/test.rs
stellar-contract-env-host/src/weak_host.rs
stellar-contract-env-host/tests/integration.rs

Based on conversation today, this buries the `WeakHost` type as a private detail in the host crate and only exposes `Host`, moving all substantial logic to the `impl Env for Host` and making `impl Env for WeakHost` just upgrade the weakref and call through to the `Host` impl. Then it renames `Val` to `RawVal` and reorganizes things a little so `EnvVal<Host>` ought to be relatively convenient to use from contract unit-test code. Adds an integration test to show how that works. I _think_ this is a good path, though we might want to bake-in a duplicate set of `EnvVal`-taking and returning default methods that do the `host.foo(ev.val).in_env(&host)` pattern?

Rename Val -> RawVal, reorganize host to make WeakHost crate-private.

---

.github/workflows/rust.yml
Makefile
stellar-contract-env-common/Cargo.toml
stellar-contract-env-common/src/rt.rs
stellar-contract-env-common/src/symbol.rs
stellar-contract-env-guest/Cargo.toml
stellar-contract-env-guest/src/guest.rs
stellar-contract-env-guest/src/lib.rs
stellar-contract-env-host/Cargo.toml

Disable the std feature on guest crate.
The common crate defaults to having std enabled and passes that down to the xdr lib. We don't want anything to pull in std in the wasm when guest is in use.
N/A

Disable common's std feature on guest crate

---

.github/workflows/rust.yml
stellar-contract-env-host/Cargo.toml
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/lib.rs
stellar-contract-env-host/src/vm.rs

This adds a new optional feature `vm` to the host crate which supports a wasmi VM that resolves host functions against a static list and routes them into the Host object using glue functions.
Lots more wiring to do here but it's a start.

Begin sketch of VM support in host crate.

---

stellar-contract-env-common/src/raw_val.rs

Add TryFrom<RawVal> to RawValType.
So that anywhere RawValType is used as a generic parameter we can assume that the type specified for the parameter also has TryFrom<RawVal>, which all RawValType's do.
N/A

Add TryFrom<RawVal> to RawValType

---

stellar-contract-env-common/src/env_obj.rs

Allow EnvObj to be created by the sdk.
The SDK gets RawVal's back from the Env (Host/Guest), but needs to convert them into EnvObjs, but there's no way for it to do that because the type is privately an EnvVal.
N/A

Allow EnvObj to be created by sdk

---

.github/workflows/all.yml

Add workflow that runs after a commits check suite completes.
We have an issue with terraform / GitHub repo config that changing the required checks is tedious and time consuming. This workflow is an attempt to have a single action workflow/job that will succeed when all others have succeeded, so we can reference this one job instead of having to reference and keep updated many jobs.
Check suite triggered workflows only run once merged to the default branch, so this is untested until merged.

Add workflow that runs after a commits check suite completes

---

stellar-contract-env-common/Cargo.toml
stellar-contract-env-common/src/env.rs
stellar-contract-env-common/src/env_val.rs
stellar-contract-env-common/src/lib.rs
stellar-contract-env-common/src/raw_obj.rs
stellar-contract-env-common/src/raw_val.rs
stellar-contract-env-guest/src/guest.rs
stellar-contract-env-host/Cargo.toml
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/vm.rs
stellar-contract-env-host/src/vm/dispatch.rs
stellar-contract-env-host/src/vm/func_info.rs
stellar-contract-env-host/src/weak_host.rs
stellar-contract-env-host/tests/integration.rs

This moves the declaration of host function information (names, type signatures, mutability-of-self, enclosing module, wasm import names, etc.) into a single x-macro (higher-order macro) that then calls back several different site-specific macros where the information is used:
1. The site of `trait Env` being declared
2. The site of all guest `extern "C"` native module decls.
3. The site of the `impl Env for Guest` that forwards all methods through to the `extern "C"` modules.
4. The site of `impl Env for WeakHost` that forwards all methods through to `Host`
5. A new site of resolving imports during WASM module instantiation in the VM.
6. A new site of dispatch functions that unpack args and forward the call to `Host` when the VM calls a resolved import.
It does not change implementations …

Implement host-function boilerplate through x-macros.

---

stellar-contract-env-common/src/env_obj.rs
stellar-contract-env-common/src/env_val.rs
stellar-contract-env-common/src/has_env.rs
stellar-contract-env-common/src/lib.rs

Remove HasEnv trait.
Nothing depends on the trait itself, there are just unrelated implementations that do not interact with each other. The trait doesn't appear to add anything of value, other than introduce another type that downstream code must know about which is inconvenient. We can always add it back if we need it.
Learning Rust still.

Remove HasEnv trait

---

stellar-contract-env-common/src/env_val.rs
stellar-contract-env-host/src/host.rs

Make Envs passed around as refs and clone downstream.
It reduces the clones that need to be littered throughout code upstream. In many other functions like in_env we're passing references and cloning internally. This brings more fns into consistency with this pattern.
N/A

Make Envs passed around refs and clone downstream

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-common/src/env_obj.rs
stellar-contract-env-common/src/env_val.rs
stellar-contract-env-common/src/raw_obj.rs
stellar-contract-env-guest/src/guest.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/weak_host.rs
stellar-contract-env-host/tests/integration.rs

Make return values `RawObj` that are guaranteed to be that type.
It simplifies the SDK since the SDK will be assuming the values are RawObj's anyway, and this allows it to do so without unchecked/unsafe blocks of code.
Note that it is important that host fn inputs are only `RawVal`s because the host should not make any assumptions about what the guest has provided as arguments.
N/A

Make ret values RawObj that are guaranteed to be

---

Cargo.toml

Use resolver v2 for workspace.
Cargo uses v2 for individual projects, or for workspaces where the root of the workspace is a module. For "virtual workspaces," which are workspaces that do not contain a crate at the root, v1 is the default. Both versions of Cargo's resolver are problematic (https://github.com/rust-lang/cargo/issues/10636, https://github.com/rust-lang/cargo/issues/4463) because neither consistently build individual crates in a workspace. However, v1 is particularly worse because it will not isolate target specific directives from each other. This means that if you use v1, dependencies that are intended only for an x86 target may be linked into a build that is only targeting wasm32. Even though v2 is not perfect, it will isolate targets properly.
This doesn't cause any …

Use resolver v2 for workspace

---

stellar-contract-env-common/src/env_val.rs

Add `From<EnvVal<E, TaggedVal<T>>>` for `RawVal`.
So that we can conveniently call `.into()` on an `EnvVal` that contains a `TaggedVal` to convert the value directly into a `RawVal. In situations where we can to move a value into a `RawVal` this is more convenient than using the `.as_ref().clone()` route.
N/A

Add From<EnvVal<E, TaggedVal<T>>> for RawVal

---

stellar-contract-env-common/src/val.rs

Require all `Val` impls to be `Into<RawVal>`.
Round out expectations to match the fact that they are all `AsRef<RawVal>`.
N/A

Require all Val impls to be Into<RawVal>

---

stellar-contract-env-common/src/env_val.rs
stellar-contract-env-host/tests/integration.rs

Add `as_` and `to_` fns to `EnvVal`. Also, remove the `_ref` suffix from the existing `as_` fns.
The `as_` and `to_` fns are helpful in situations where the trait is ambiguous, and having all the different variations makes the API feel more complete and accessible.
The `_ref` is unnecessary on the tail of the `as_` functions, since the convention is that `as_` fns return borrowed values, and so the ref is implied.
See this link for the conventions:
https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv
N/A

Add as_ and to_ fns to EnvVal

---

stellar-contract-env-common/src/env_val.rs

Add `TryFrom<EnvVal<_,RawVal>>` for `TaggedVal<_>` and `EnvVal<_,TaggedVal<_>>`.
For convenient conversions from `EnvVal`s containing `RawVal`s into `TaggedVal`s and their `EnvVal` variant.
N/A

Add TryFrom<EnvVal<_,RawVal>> for TaggedVal<_>/EnvVal<_,TaggedVal<_>>

---

stellar-contract-env-common/src/env_val.rs
stellar-contract-env-common/src/lib.rs
stellar-contract-env-common/src/raw_val.rs
stellar-contract-env-common/src/tagged_val.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs

Make `EnvValConvertible` blanket impl:
- `IntoEnvVal`, which is blanket impl for all `Into<EnvVal>`
- `TryFrom<EnvVal>`
And add explicit `IntoEnvVal` impls for all `RawVal`s and `TaggedVal`s.
I noticed that in the SDK I was implementing both TryFrom and EnvValConvertible with the same logic for types. We should just ask types to implement each fn once, and EnvValConvertible can rely on the presence of the TryFrom when going from EnvVal to an impl of EnvValConvertible since the entire value, including the Env, is held in a single value. All types should be able to provide a TryFrom in this direction.
I also noticed that most types in the SDK are going to be able to impl the reverse by simply implementing `Into<EnvVal>`.
Overall this simplifies the SDK because we can use a blanket impl to …

Split EnvValConvertible into Into<EnvVal>, IntoEnvVal, TryFrom<EnvVal>

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs

Change `bigint_sh*` fns to `i32`/`RawVal` shift arg.
In the words of @graydon, if anyone has more bits than that to shift, they're in trouble resource wise.
N/A

Change bigint_sh* fns to i32/RawVal shift arg

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs

Change types of some BigInt fns from Object to RawVal or builtins.
The values are not objects and are either i32's encoded in RawVals, or they are i64/u64 that can be transmitted over the boundary as they are.
N/A
cc @graydon @jayz22

Change types of some BigInt fns

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs

Change arguments to BigInt gcd fn to take a second BigInt.
The gcd fn finds the greater common divisor of two BigInts.
N/A
cc @graydon @jayz22

Fix BigInt gcd fn

---

stellar-contract-env-host/src/lib.rs
stellar-contract-env-host/src/vm.rs

Rename `VM` to `Vm`.
Editors like VSCode think the `VM` type is a constant or static if it is all capitalized, because Rust naming conventions reserve all caps for consts and statics. The conventions say to only capitalize the first letter of words in type names and to treat acronyms as a single word where only the first letter is capitalized. https://rust-lang.github.io/api-guidelines/naming.html
N/A

Rename VM to Vm

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-common/src/env_val.rs
stellar-contract-env-host/src/host.rs

Add a couple of host functions:
- `obj_to_u64`
- `obj_to_i64`
Provide implementation for essential host functions. 
This is just a start, still many more to do.

Add impl to `obj_to_u64`, `obj_to_i64`

---

stellar-contract-env-common/src/env_val.rs
stellar-contract-env-common/src/lib.rs
stellar-contract-env-host/src/host.rs

Move `into_val` from `EnvValConvertible` to `IntoEnvVal`.
The fns only dependency is on `IntoEnvVal`, and so it could live in that trait and be available on all impls of that trait independent of the `EnvValConvertible`, so I think it belongs there. It simplifies call sites that do not need to depend on the full convertible and that can specify their constaints as only the into trait.
[TODO or N/A]

Move into_val from EnvValConvertible to IntoEnvVal

---

stellar-contract-env-common/src/raw_val.rs
stellar-contract-env-common/src/tagged_val.rs

Change in_env to move.
The fact we used a ref for self here is probably a mistake since this fn is taking a value and wrapping it into a new thing.
This doesn't really matter.

Change in_env to move

---

stellar-contract-env-common/src/env_val.rs

Undo the recent change where we used try_into between RawVal and TaggedVal inside the i64 conversion fn.
It increased the size of the wasm by 20-30 bytes per invocation. 
It's unclear why.

Undo change that increased wasm size

---

stellar-contract-env-common/Cargo.toml
stellar-contract-env-guest/Cargo.toml

Remove old panic_handler feature.
The panic handler was moved into its own crate that the sdk only depends on in the wasm builds. This is simpler to manage with Cargo than having a multi-crate deep feature.
N/A

Remove old panic_handler feature

---

stellar-contract-env-common/src/env_val.rs
stellar-contract-env-host/src/test.rs

Reserve pos i64 type for i64 typed values, making u64 always transmitted as an object.
The existing u64 impl that uses the pos i64 type for small values is an optimization at a cost of type safety. 
The problem is a user could invoke a contract with an `i64` or an `u64`, and the value could be consumed as either on the contract side if the value was positive and fit into 63-bits. This lack of determinism could make it easier to introduce bugs into contracts or into applications calling contracts.
For example, an application developer might test their application with values that fit into 63-bits, and they might call a contract with an argument using the `u64` type. However, the contract might have been written to assume an `i64` input. The application developer might think everything is …

Reserve pos i64 type for i64 typed values

---

stellar-contract-env-common/src/env_val.rs

Add conversion as/to_object fns to EnvVal when EnvVal contains an Object.
We have conversion functions in the form of as/to_raw and as/to_tagged, but the tagged function may not be super obvious that it returns an object when EnvVal contains an object. To increase code readability having another version of this function that is identical but adds that 'object' context to the reading should make some code clearer.
N/A

Add conversion as/to_object fns to EnvVal

---

stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs

Add remaining `vec` hostfns:
- put
- get
- del
- take
- insert
- append
Fixed:
- pop
The only one omitted is `vec_drop` which is redundant with `vec_take`.
Add their corresponding test cases.
[TODO or N/A]

Add remaining vec hostfns and tests

---

stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/lib.rs
stellar-contract-env-host/src/storage.rs
stellar-contract-env-host/src/vm.rs

This is a sketch of the support code for the contract-data system. It doesn't include any host functions yet, just the plumbing underneath (footprint recording and enforcement and an in-memory OrdMap containing XDR data values).
I'll provide host functions and connect it up to core next, but this is a first step.

Sketch contract-data storage w/ footprint recording/enforcing.

---

stellar-contract-env-host/src/lib.rs
stellar-contract-env-host/src/storage.rs

Small change that updates the ContractID type to a Hash and makes clearer the two different storage footprint modes by splitting the constructor.

Clarify construction modes of storage

---

stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/storage.rs
stellar-contract-env-host/src/test.rs
stellar-contract-env-host/src/vm.rs

A few pieces here:
- Add a new `Host::with_storage` constructor so we can provide a `Storage` object.
- Add a new `HostImpl::context` which is a stack of `Frame` objects (currently just storing the current `ContractID`)
- Push (and automatically pop) such `Frame` objects when invoking a contract in `Vm`
- Implement `get_contract_data` using these (and a couple other helpers)

Add plumbing for implementing storage host functions

---

stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/vm.rs

I'm not sure why I had things wired up to use `dyn Error` before but this seems harmless and is necessary (or something like it) for calling vm methods from host (eg. cross-contract invocation)

Allow mutual nesting of HostError and wasmi::Error

---

stellar-contract-env-common/src/env_val.rs
stellar-contract-env-common/src/lib.rs
stellar-contract-env-common/src/tuple.rs

Add conversions for tuples to and from RawVal.
To make it convenient to pass tuples across the host/guest boundary, without having to manually craft vecs.
Close stellar/rs-stellar-contract-sdk#107
cc @jonjove 
N/A

Conversions for (T0,T1,...)<>Rawval

---

stellar-contract-env-common/src/tuple.rs

Make tuples impl `IntoEnvVal<_, RawVal>` instead of `IntoEnvVal<_, TaggledVal<TagOvject>>`.
This was a mistake on my part. All the types implement IntoEnvVal for RawVal, because RawVal is the common Val impl that applies to all types, and so it is a common ground for them all to interoperate. By being convertible into that the type can be placed inside Vecs, Maps, etc.
[TODO or N/A]

Make tuples impl IntoEnvVal<_, RawVal>

---

stellar-contract-env-common/src/tuple.rs

Set the type of the idx to u32.
The type was defaulting to some other type.
[TODO or N/A]

Fix type of idx used in tuple hostfn access

---

stellar-contract-env-common/src/option.rs

Add support for Option<T> <> RawVal conversion.
Contract developers will probably want to store Option<T>.
The `Env` trait and `RawVal` definitions don't give us a native way to store optionals. So the use of a `Vec` for this is a bit of a hack. There's a discusion [in Discord](https://discord.com/channels/897514728459468821/982314893237714967) for alternatives if we decide to support them.

Add support for Option<T> <> RawVal conversion

---

stellar-contract-env-common/src/env_val.rs

Add `IntoEnvVal<_, RawVal>` impl for `TaggedVal`/`Symbol`.
It's not possible to into a `RawVal` for a `Symbol`, because a `Symbol` is a `TaggedVal<TagSymbol>` and `TaggedVal` was missing the impl.
`TaggedVal` is a type that has `IntoEnvVal` impls for multiple `Val` types. It might get annoying to specify the destination type, but if so we can probably remove the other impl that already exists, as it probably isn't meaningful to keep.

Add IntoEnvVal<_, RawVal> impl for TaggedVal/Symbol

---

stellar-contract-env-common/src/lib.rs

Export SymbolStr.
So that the SDK code can get a string from a Symbol.

Export SymbolStr

---

stellar-contract-env-common/src/symbol.rs

Add a is_empty and to_str to SymbolStr.
Adding the to_ conversion function simplifies some call sites instead of relying on From/Into.
[TODO or N/A]

Add a is_empty and to_str to SymbolStr

---

Cargo.lock
stellar-contract-env-host/Cargo.toml
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/vm.rs

Add functions for getting a list of WASM functions from the loaded WASM in the `Vm`.
So that tools like the CLI can inspect the functions.
@graydon and I discussed a couple approaches to doing this. The first was to fork wasmi and to expose these details that it already has. However, @graydon pointed out that the parity_wasm crate can already expose these details to us, and we could load the wasm via it first then continue to use wasmi from there. This does appear to work elegantly, assuming that the wasmi crate retains this parity_wasm entry point.
N/A
cc @graydon Adding you as a reviewer, but will be merging aggressively. Feel free to leave feedback post-merge.

Export WASM file functions in VM

---

stellar-contract-env-host/src/vm.rs

Export custom sections from Vm.
So that tools like the CLI, and the macros used in generating cross contract clients, can extract the custom section containing the specification.
[TODO or N/A]
cc @graydon

Export custom sections from Vm

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs

Replace `call0...4` function with a single `call` function that takes a single `ScVec` object containing variable number of arguments. 
Variadic function is a useful case for cross-contract calling, brought up in the CAP-51 discussion and the CAP has been updated to include it. Having multiple `callx` functions seem redundant. 
[TODO or N/A]

Use a single variadic function for cross-contract call

---

Cargo.lock
stellar-contract-env-common/Cargo.toml
stellar-contract-env-common/src/raw_val.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/host_object.rs
stellar-contract-env-host/src/lib.rs
stellar-contract-env-host/src/storage.rs
stellar-contract-env-host/src/test.rs
stellar-contract-env-host/src/vm.rs

This updates definitions to match core (and subsequently XDR) definitions that landed with the contract-data branch. It does include removal of all the in-progress host object types, including bigint, which was removed upstream in core (and thus XDR). They will need to be re-added as they're finalized.

Contract data update

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs

Remove ledger env functions:
- `get_current_ledger_num()`
- `get_current_ledger_close_time()`
- `pay(...)`
- `account_balance(...)`
- `account_trust_line(...)`
- `trust_line_balance(...)`
They aren't defined in CAPs, and are left over from experimentation. Removing so they don't unintentionally inform our implementation or create confusion.
[TODO or N/A]

Remove some ledger fns

---

stellar-contract-env-common/src/env.rs

Remove $ from hostfns.
The dollar signs were added to ensure that no externed fn from user code could collide with a hostfn, but this is unnecessary because they end up in different wasm export/import tables. And all the imported fns are namespaced anyway.
[TODO or N/A]

Remove $ from hostfns

---

Cargo.lock
stellar-contract-env-common/Cargo.toml
stellar-contract-env-common/src/raw_val.rs
stellar-contract-env-common/src/tagged_val.rs
stellar-contract-env-host/Cargo.toml
stellar-contract-env-host/benches/calibrate_wasm_insns.rs
stellar-contract-env-host/src/budget.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/lib.rs
stellar-contract-env-host/src/vm.rs

This PR does 3 main things:
1. Adds a new `Budget` type to `Host` that can be queried or modified by host and vm code to record cost-incurring events, scale them by cost factors, and compare them to cost limits.
2. Bumps wasmi to a recent commit I pushed to https://github.com/stellar/wasmi which gives it some basic step-metering and memory-metering capability (calling back through the `Externals` interface it already uses to call back to host functions), wiring that up to the `Budget` type.
3. Adds a benchmark that calibrates (using synthetic wasm code of varying lengths) a basic CPU-instructions-per-wasm-instruction in terms of linux `perf` hardware performance counters. It's fairly crude but gets us a decently stable number. On my system it produces this:

Add preliminary support for metering and cost budgets.

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs

Removes stale `get_last_operation_result` host function that no longer exists. Adds host functions specified in CAP-52 without implementations.
The CAP-52 host functions are need for the implementation of CAP-54.
New host functions aren't actually implemented yet.

Add host functions for CAP-52

---

stellar-contract-env-host/Cargo.toml
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/lib.rs

Adds a new feature that facilitates testing.
Makes it possible to call contract data functions from native tests.
It would be better if we didn't need to use this "testutils" feature and instead could do this through `cfg(test)`.

Add testutils feature and use it to emulate a Frame

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs

- Expose `try_call` as a public host function through macro. 
- Some minor cleanup.
Previously it was added as a public crate function but not a host function.
We decided that it is ok for `try_call` to return a `Result` that is always `Ok`.
[TODO or N/A]

Expose `try_call` as a public host function

---

Cargo.lock
stellar-contract-env-common/src/bitset.rs
stellar-contract-env-common/src/env_val.rs
stellar-contract-env-common/src/lib.rs
stellar-contract-env-common/src/object.rs
stellar-contract-env-common/src/option.rs
stellar-contract-env-common/src/raw_val.rs
stellar-contract-env-common/src/status.rs
stellar-contract-env-common/src/symbol.rs
stellar-contract-env-common/src/tagged_val.rs
stellar-contract-env-common/src/tuple.rs
stellar-contract-env-host/Cargo.toml
stellar-contract-env-host/benches/calibrate_wasm_insns.rs
stellar-contract-env-host/src/budget.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/storage.rs
stellar-contract-env-host/src/test.rs
stellar-contract-env-host/src/vm.rs

A few separate fixes here, probably worth reading by @leighmcculloch and @jayz22 (and maybe @sisuresh since it touches some of your tests) but nothing substantially weird or bad:
- Move from ()-as-an-error in common to a specific named `ConversionError` struct
- Make the Debug impls much better in common, using enum names and so forth
- Make the budget arithmetic more efficient to check on the fly and partially update (as events grow)
- Fix a couple error codes
- Mostly: remove a ton of unwrap and should_panic in test code
One notable aspect of the last point is moving to `assert_matches!(...)` macros and matching on the error enum cases rather than the string messages in the error codes. I think this is a better thing to lean on for testing, not least because it lets us do …

Misc gardening

---

stellar-contract-env-host/src/lib.rs

Theoretically we can try to make downstream clients such as stellar-core use "the same" `im_rc` version through matching `Cargo.toml` file entries; but it is less error-prone and friendlier to multi-versioning if we just re-export the version used by the host from the host itself.

Re-export the exact version of im_rc used in the host.

---

stellar-contract-env-host/src/host.rs

Implements `account_get_{low,medium,high}_threshold` and `account_get_signer_weight`.
These are used in CAP-54.
No tests.

Implement account signer functions

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs

Pass in bigint objects to `bigint_shl/shr/pow` fn signatures, and provide sign and overflow checks within these functions. 
The `num_bigint` api of `shl`, `shr`, `pow` has internal checks for [sign](https://docs.rs/num-bigint/latest/src/num_bigint/biguint/shift.rs.html#13) and [overflow](https://docs.rs/num-bigint/latest/src/num_bigint/biguint/power.rs.html#25), which may panic if the inputs do not fit. Instead of restricting our hostfn api (e.g taking a `u32` as the exponent in `bigint_pow`), we should still pass those parameters as `BigInt` and check their validity from within the host functions. This makes the bigint hostfn apis more uniform and easier to maintain. 
[TODO or N/A]

Pass `Object` type to bigint `shl`, `shr`, `pow` fn signatures

---

stellar-contract-env-common/src/symbol.rs

Remove `Copy` from `SymbolIter`.
Making an iterator copyable creates some footguns because it's easy to copy it when we should otherwise be borrowing.
[TODO or N/A]

Remove Copy from SymbolIter

---

stellar-contract-env-common/src/tuple.rs

Support 1-ary tuple conversion to/from RawVals.
There's no reason to support it and @jonjove has pointed out it would be convenient in some cases. When I originally wrote this I thought Rust didn't have 1-ary tuples, but @jonjove pointed out it does. I was merely using the wrong syntax for doing so.
Close #178 
[TODO or N/A]

Support 1-ary tuple conversion to/from RawVals

---

stellar-contract-env-common/src/env.rs

Rename call module from "c" to "d".
Because it collides with crypto, and "d" stands for dispatch.
None

Rename call module from 'c' to 'd'

---

stellar-contract-env-common/src/raw_val.rs

Derive `Eq`, `PartialEq` for `ConversionError`.
So that `Result`s that contain the `ConversionError` can be compared.
[TODO or N/A]

Derive Eq,PartialEq for ConversionError

---

Cargo.lock
stellar-contract-env-host/Cargo.toml
stellar-contract-env-host/benches/calibrate_host_ops.rs
stellar-contract-env-host/benches/calibrate_wasm_insns.rs
stellar-contract-env-host/benches/common.rs
stellar-contract-env-host/benches/common/measure.rs
stellar-contract-env-host/benches/common/modelfit.rs
stellar-contract-env-host/src/budget.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/lib.rs
stellar-contract-env-host/src/vm.rs

I'm out of time for this evening, but I promised @jayz22 a little material and this is as far as I got. It compiles and half-works, but doesn't work enough to merge just yet. You're welcome to try to brush it up into something mergeable, or just stare at it and get an idea for the direction I think we should be going / where I'm going to try to take it next week.
(this addresses #160)
What's here:
- General cost models rather than just linear factors. A cost model is a parameterized function with a constant, linear, log, log-base, and quadratic term. These parameters will eventually be loaded from ledger `CONFIG_SETTING` entries, but for now they're all zero except the one I added for tracking CPU insns per WASM insn.
- Uniform interface to multiple cost models in multiple different …

Overhaul the budget system with general cost models, add model fitting.

---

.github/workflows/rust.yml

Use toolchain action to install Rust.
Rustup started to fail to update the version of Rust on some windows GitHub Action runners. https://github.com/actions/runner/issues/1993
Installing with the toolchain action seems to work though, so maybe there is something subtle we were doing wrong with how we were using rustup that only just now became a problem.
[TODO or N/A]

Use toolchain action to install Rust

---

.github/workflows/rust.yml
Makefile
rust-toolchain.toml

Use the toolchain file in GitHub Actions.
There's no reason to respecify values that are included already in the toolchain file since the action will load them from there.
[TODO or N/A]

Use the toolchain file in GitHub CI

---

stellar-contract-env-host/benches/calibrate_host_ops.rs
stellar-contract-env-host/benches/common/measure.rs
stellar-contract-env-host/src/budget.rs
stellar-contract-env-host/src/host.rs

This extends the metering infrastructure with a general charging-point for host objects (further down the funnel of ways-objects-can-be-added) and adds support for multiple calibrations in a single bench. Also calibrates empty vs. cell costs separately and does map in addition to vec (map is currently quite a bit more expensive -- im has a small-vec optimization but _not_ a small-map optimization, so we'll have to add one ourselves).

Add more host-function / host-object metering infrastructure

---

stellar-contract-env-common/src/tagged_val.rs

Make TaggedVal fns const.
So that they can be called from const contexts at compile time.
[TODO or N/A]

Make TaggedVal fns const

---

stellar-contract-env-common/src/lib.rs
stellar-contract-env-common/src/version.rs

This is a first attempt at the problem of declaring interface versions. It's _mostly_ just a comment explaining things, plus a constant. This relates to https://github.com/stellar/stellar-core/pull/3471 which is for implementation versioning.

Add ENV_INTERFACE_VERSION and a big comment

---

stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/lib.rs
stellar-contract-env-host/src/test.rs

Add machinery to register a test contract and call it.
Testing multiple contracts is basically impossible right now. This facilitates calling contracts by contract identifier.
The interface isn't amazing.

Register Test Contract

---

Cargo.lock
stellar-contract-env-common/Cargo.toml
stellar-contract-env-common/src/lib.rs
stellar-contract-env-common/src/meta.rs
stellar-contract-env-macros/Cargo.toml
stellar-contract-env-macros/src/lib.rs

Generate meta containing the interface version.
So that the SDK can embed this information into WASM files.
Unfortunately generating the XDR in the SDK is somewhat problematic, because we need the literal value to be present at the time the macro runs, and the constant from another crate is not particularly useful unless we have the SDK macro crate depend on the env crate. If we do that, we run into the risk that the SDK macro crate will depend on a different version of the env crate as the SDK itself which would cause the WASM to lie about which env interface it was built with.
Given all that complexity risk, it seems simpler to build the meta within the env crate. After all this meta being built is the meta for the environment only.
The env meta XDR and the macro can be expanded to …

Generate meta xdr containing interface version

---

stellar-contract-env-common/src/lib.rs
stellar-contract-env-macros/src/lib.rs

Export meta under mod name.
To group related variables without cluttering the root namespace of the crate.
Follow up to https://github.com/stellar/rs-stellar-contract-env/pull/210
Close https://github.com/stellar/rs-stellar-contract-sdk/issues/142
[TODO or N/A]

Export meta under mod name

---

stellar-contract-env-host/src/host.rs

Change `ContractFunctionSet` to trait.
Makes it easier to do some wiring in the SDK.
This whole interface still needs work.

Change ContractFunctionSet to trait

---

stellar-contract-env-host/src/host.rs

Use a test frame when calling a test contract, so that frame-dependent host functions work.
Fixes a bug introduced in #214.
N/A

Use test frame when calling a test contract

---

stellar-contract-env-host/src/budget.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test.rs

Resolves https://github.com/stellar/rs-stellar-contract-env/issues/180 
Previously the `map_prev_key` , `map_next_key` replicates the im_rc's behavior: if the given key exists, returns itself, which is not useful for implementing iterators. 
[TODO or N/A]

Fix map prev and next key to do strict comparison

---

Cargo.lock
stellar-contract-env-common/src/raw_val.rs
stellar-contract-env-common/src/status.rs
stellar-contract-env-host/Cargo.toml
stellar-contract-env-host/src/budget.rs
stellar-contract-env-host/src/events.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/storage.rs
stellar-contract-env-host/src/test.rs
stellar-contract-env-host/src/vm.rs

This is a fairly large (not terribly deep, but important and systematic) change that implements my best attempt at addressing the conclusions of our conversation in https://github.com/stellar/rs-stellar-contract-env/issues/205
If it's not _totally_ objectionable, I'd like to ask for a fast review and landing on: it'll bitrot almost instantly if anyone lands anything else, and it touches almost every function in host and test.
What it does:
- Splits the diagnostic-and-error-handling functionality in HostError into two:
- `HostError` retains a pure `Status` value (not `ScStatus`, though they're mostly interchangeable) and is used for _error handling_ only
- Diagnostic functionality is transferred to `DebugEvent` which can contain a small vec of `RawVal`s (possibly including a `Status`) as …

Change HostError to just a Status, move diagnostic info to DebugEvent.

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test/binary.rs

Just like `vec_slice`, the `binary_slice` should take start and end index instead of the start and length. 
[TODO or N/A]

Fix `binary_slice` to take start and end index

---

Cargo.lock
stellar-contract-env-common/src/env.rs
stellar-contract-env-common/src/unimplemented_env.rs
stellar-contract-env-guest/Cargo.toml
stellar-contract-env-guest/src/guest.rs
stellar-contract-env-host/Cargo.toml
stellar-contract-env-host/src/events.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/weak_host.rs
stellar-contract-env-host/tests/integration.rs

This addresses two sets of related problems we've been discussing recently:
- How to get contract-memory slices into binaries when `Env=Host` (call this "native" or "test contract", however you like): #179
- How to get richer debug logging from contracts _at least_ (perhaps only) when building `Env=Host` (multiple args, format strings, static string args): #229, #181, #205 
The common problem / issue here (and what took so long, I tried a lot of different unsatisfying approaches) is "what's the safest and least-terrible way of receiving pointers-into-contract-memory on the host when `Env=Host`". We know what to do when `Env=Guest` -- a contract pointer is a linear memory address, a u32 -- but when `Env=Host` it means we're sharing a process with the host and we might find it ugly, unsafe …

Implement contract memory access and debug formatting

---

stellar-contract-env-common/src/object.rs
stellar-contract-env-host/src/host.rs

Add ScVal to/trom Object impls.
So that there are more seamless TryFrom conversions to and from ScVal backed by TryConvert, not just ScObject.

Add ScVal to/trom Object impls

---

stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/host/error.rs

This adds an `impl Error for HostError` (which was accidentally lost when removing the use of `thiserror`) as well as a couple helper functions that factor out error-generating paths in host function.

Impl std::error::Error for HostError and add some helpers

---

stellar-contract-env-common/src/env_val.rs

Loosen EnvVal value constraints.
So other types, like `ScVal`, can implement traits like `TryFromVal`.

Loosen EnvVal value constraints

---

stellar-contract-env-common/src/env_val.rs

More flexible TryFromVal/IntoVal traits.
The `TryFromEnvVal` and `TryFromVal` traits are bound together. You must always implement both, which is unnecessary. Instead of saying both must be implemented and providing a default implementation, we can just say that the latter is always implemented automatically for the former, but this allows someone to only implement the latter if that makes more sense.
The same for the `IntoEnvVal` and `IntoVal` traits.

More flexible TryFromVal/IntoVal traits

---

stellar-contract-env-common/src/env_val.rs

Impl `TryIntoEnvVal` for all `EnvVal<>: TryInto`.
To surface the useful `.try_into_env_val()` and `.try_into_val()` functions for types that implement `TryFrom<EnvVal<>>` or `TryInto<> for EnvVal<>`.
This new blanket impl will be the first time for some types that multiple implementations are possible for this trait, and so there will be some places in the SDK that will have ambiguous uses of these functions that will require some type annotations. I've already run through them and there are only a half dozen that are easy to fill in.

Impl TryIntoEnvVal for all EnvVal<>: TryInto

---

stellar-contract-env-common/src/env.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test/bigint.rs

Resolves https://github.com/stellar/rs-stellar-contract-sdk/issues/219 
SDK side change will follow this. 
Add two `BigInt` host functions for debugging. 
- `bigint_to_bytes_be` to dump the digits as bytes
- `bigint_to_radix_be` to dump the digits as numbers in any base < 256
Along the change some hostfn impls gets shuffled into their correct (declared) order.  
[TODO or N/A]

Add BigInt fns to convert to bytes / array of digits

---

stellar-contract-env-common/src/raw_val.rs
stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/test/binary.rs

Remove implementations that make `u8` convertible with `RawVal`.
`u8` is not a type supported by the contract system, and so any use of u8 is a constrained space u32. We should just do the conversions to u32 when we need a value that has a max of a u8, rather than introducing this convenience method, otherwise developers may store what they think is a u8 into a contract field, then increment it elsewhere past the valid value of a u8.
There are also some inconveniences of making this a RawVal, as it prevents us from implementing some types with alternative implementations for u8, like the Vec type in the SDK.
cc @jayz22 @graydon @jonjove @sisuresh

Remove u8 as a RawVal

---

stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/host/conversion.rs

Split out arg conversion functions into a new file.  Clean up existing (repetitive) conversion code to use those functions. 
Relates to https://github.com/stellar/rs-stellar-contract-env/issues/154.
Clean up the host file, to make it smaller and more readable.
This is a continuous effort.

Split conversion-related code out of host into a new file.

---

stellar-contract-env-host/src/host.rs
stellar-contract-env-host/src/host/conversion.rs

Clean-ups. Related to https://github.com/stellar/rs-stellar-contract-env/issues/154
Reduce the file size of `host.rs`. Splits out repetitive code into utility functions in separate files.
[TODO or N/A]

Clean-up: binary object to 32-byte fixed-array arg conversion

---

stellar-contract-env-common/src/env_val.rs

Add conversions from `ScVal` to `()`, `bool`, and `u32`.
Needed to make the `call_external` macro work correctly.
This doesn't include all relevant types.

Add conversions from ScVal to (), bool, and u32

---

stellar-contract-env-common/src/env_val.rs
stellar-contract-env-host/src/host.rs

Reverts #267, introduces a simpler workaround where `invoke_function` returns a `RawVal` instead of `ScVal`.
Closes #268
Needed to make `call_external` macro work.
This doesn't feel like the right approach in the long term.

Simplify invoke_function for macro

---

soroban-env-host/src/host.rs
soroban-env-host/src/host/validity.rs
soroban-env-host/src/test/binary.rs

Reopens https://github.com/stellar/rs-soroban-env/pull/291
- Reverts https://github.com/stellar/rs-soroban-env/pull/290, which reverted https://github.com/stellar/rs-soroban-env/pull/279. Bring back the index validity checking code.
- Adds the fix, improves interface, adds tests
[TODO or N/A]

Revert "Revert "Refactor index validity-checking code into a new file ""

---

soroban-env-host/src/host.rs
soroban-env-host/src/host/conversion.rs
soroban-env-host/src/host/data_helper.rs

Split out some storage access, data massage code into a new data helper file. Some code goes into the conversion helper file.  
Shorten the `host`, make it clearer in order to prepare for some cost budget/metering work. 
[TODO or N/A]

Clean up host storage/data related code

---

soroban-env-host/src/budget.rs
soroban-env-host/src/host.rs
soroban-env-host/src/test/lifecycle.rs
soroban-env-host/src/vm.rs

- Remove the `drop` trait from `FrameGuard` which automatically cleans up after frame goes out of scope. 
- Add a `roll_back` function that does the clean up.
- Wrap all push_frame calls in `with_frame_guard`, which automatically calls `commit` on success and `roll_back` on err. 
- Add metering to frame pushing and popping.
Preparing for the metering change. 
The frame guard functions needs to be metered (it needs to copy data), which may fail due to reaching budget limit, therefore they need to return `Result`. `drop` function does not allow that.
As discussed with @graydon , this is the alternative "cleanup-upon-going-out-of-score" pattern to `drop`. 
[TODO or N/A]

Replace FrameGuard drop trait with guarded closure; add metering

---

Cargo.lock
soroban-env-host/Cargo.toml
soroban-env-host/benches/calibrate_host_ops.rs
soroban-env-host/benches/calibrate_wasm_insns.rs
soroban-env-host/benches/common/measure.rs

This adds support for running the budget calibration benchmark code on M1 / apple silicon macs.
(It might also work on intel macs, I will give it a try tomorrow morning, but this should be enough to unblock @jayz22 on calibration)

Support calibration benches on apple silicon macs

---

Cargo.lock
Cargo.toml
soroban-env-common/Cargo.toml
soroban-env-common/src/array.rs
soroban-env-common/src/lib.rs
soroban-env-common/src/raw_val.rs
soroban-env-common/tests/array.rs
soroban-env-host/src/host.rs

Add conversions between RawVal and fixed-size u8 arrays and slices.
Convenience.
Close #303 
I originally intended to do all fixed-size arrays, not just u8, but because IntoVal contains generics in its type, we can't implement both T and u8 even though u8 is not a RawVal because of limitations in the compiler not checking generic types in traits. I've opted for u8 because I think it's the type that will benefit most from having fixed array val conversion.

Add conversions between RawVal and [u8; N]

---

soroban-env-host/src/host.rs
soroban-env-host/src/ledger_info.rs
soroban-env-host/src/lib.rs

Reverts part of #350 and only exposes `LedgerInfo` in `testutils`.

Expose LedgerInfo only with testutils

---

soroban-env-common/src/symbol.rs

Add panic! messages to Symbol::from_str panics.
To better communicate why the panic has occurred.
Note that because the function these panics occur in is a const function, there are limitations for the inputs to the panic! calls meaning the strings must be simpler.

Add panic! messages to Symbol::from_str panics

---

soroban-env-common/src/raw_val.rs

Add conversion from Infallible to ConversionError.
So that in contexts where an Infallible error can sometimes get returned we can still use `?`. 
One day this might be unnecessary if https://github.com/rust-lang/rust/issues/64715 happens.

Add conversion from Infallible to ConversionError

---

soroban-env-common/src/meta.rs
soroban-env-host/src/vm.rs

This attempts to clarify the relationship between the meta version declaration and the code that checks it, as well as making it an explicit 1-point inclusive range with a "contains" check, and describing what will happen in the future in more detail.
Fixes #328

Clarify comment about meta version, fix #328

---

soroban-env-common/src/array.rs
soroban-env-common/src/env_val.rs
soroban-env-common/src/lib.rs
soroban-env-common/src/object.rs
soroban-env-common/src/option.rs
soroban-env-common/src/raw_val.rs
soroban-env-common/src/tuple.rs
soroban-env-common/src/val_wrapper.rs
soroban-env-common/tests/option.rs
soroban-env-host/src/native_contract/base_types.rs
soroban-env-host/src/native_contract/token/admin.rs
soroban-env-host/src/native_contract/token/allowance.rs
soroban-env-host/src/native_contract/token/balance.rs
soroban-env-host/src/native_contract/token/metadata.rs
soroban-env-host/src/native_contract/token/nonce.rs
soroban-env-host/src/native_contract/token/public_types.rs
soroban-env-host/src/test/basic.rs
soroban-native-sdk-macros/src/derive_fn.rs
soroban-native-sdk-macros/src/derive_type.rs

Replace TryFrom<EnvVal<>> with TryFromVal<>, and disconnect the link between TryFrom and TryFromVal.
Disconnecting TryFrom and TryFromVal is necessary because we otherwise can't provide an implementation for all Option<T> for conversion in. This is because the core lib has an impl of T to Option<T> for all T.
TryFromVal is more of a serialization interface than it is a type conversion interface, even though we present it as the latter. Given that our interface has unique and specific behavior for all types, even builtin types like Option<T>, I think we need to have it standalone and not utilize the builtin From/TryFrom traits.
There is an alternative, we could manually or with macros implement every Option<T> interface we need, but it feels like philosophically we shouldn't be saying …

Replace TryFrom<EnvVal<>> with TryFromVal<>

---

soroban-test-wasms/src/lib.rs

Previous PR forgot to actually publish the contract_data wasm as a constant.

Actually surface the contract_data.wasm as a constant

---

soroban-env-host/src/host.rs
soroban-env-host/src/host/conversion.rs
soroban-env-host/src/host_object.rs

While we're still discussing what to do with Hash, PublicKey and ContractCode, we've actually started _using_ them in some code paths -- the recent native contract stuff in particular -- and therefore we need to be able to interconvert for basic tests to continue to function (eg. the contract_data unit test in core, which forms a ContractCode LE).

Flesh out support for ContractCode, Hash and PublicKey.

---

soroban-env-common/Cargo.toml

Add `base64` feature to xdr import.
So we can save a few characters when encoding/decoding to base64.

Add base64 feature to xdr import

---

soroban-env-common/src/raw_val.rs

Add RawVal consts for i32/u32 one, neg one, min, max.
The values are well defined and are useful in the SDK in places where we need them without needing to repeatedly define consts inline to ensure the conversions happen at compile time.

Add RawVal consts for i32/u32 one, neg one, min, max

---

soroban-env-common/src/raw_val.rs
soroban-env-common/src/tuple.rs

Add conversions from ref types to RawVal.
So that we can convert from values like &T to a RawVal and not just from T to RawVal. Conversions to RawVal never need to own the type being converted from, so their ref conversions should always be supportable.
Clos_e https://github.com/stellar/rs-soroban-sdk/issues/507

Add conversions from ref types to RawVal

---

soroban-env-common/src/env_val.rs
soroban-env-common/src/lib.rs
soroban-env-common/src/raw_val.rs

Add FromVal.
There are some conversions in the SDK that won't fail but need an Env. We have previously just implemented them with infallible TryFromVal, which forces unnecessary error checking.

Add FromVal

---

soroban-test-wasms/wasm-workspace/Cargo.lock
soroban-test-wasms/wasm-workspace/Cargo.toml

Update "soroban-test-wasms" dependencies so that the wasm files would build (without local checkouts). 
This is the last step in the cycle of the compatibility-breaking `env` update process. 
[TODO or N/A]

Update test-wasms dependencies

---

soroban-env-host/src/native_contract/token/admin.rs
soroban-env-host/src/native_contract/token/contract.rs
soroban-env-host/src/native_contract/token/cryptography.rs
soroban-env-host/src/native_contract/token/public_types.rs

Make token auth match soroban-sdk-auth.
It was completely impossible to use the native token without this because the necessary types weren't exported anywhere.
Lightly tested.

Make token auth match soroban-sdk-auth

---

soroban-env-host/benches/calibrate_host_ops.rs
soroban-env-host/src/lib.rs

This just fixes a recent break and exports some types that need to be exported for the host to be used from core.

Minor fixes

---

.github/workflows/bump-version.yml
.github/workflows/rust.yml

Set the target-dir for cargo installs.
If target-dir isn't set for cargo installs the target dir will be a temporary directory and blown away, which breaks cashing of bin installs.

Set the target-dir for cargo installs

---

soroban-env-host/src/host.rs
soroban-env-host/src/test/map.rs

Associate the vec object that is created in map_keys and map_values outside of visiting the original map.
Adding an object to the host while visiting another object causes a BorrowMut error.
Close #405

Fix map_keys and map_values

---

.github/workflows/rust.yml
Makefile

Add a dry run publish step to branches that start with `release/`.
The bump version workflow creates a branch that starts with `release/`. (Ref: https://github.com/stellar/actions/blob/2eaba3e378ef8fd4e1af5e22cc17b72371c89c9a/.github/workflows/rust-bump-version.yml#L26)
We should prevent merging the release branch to main if the release would not publish successfully. That way we don't merge the bump version and then attempt the release, have it fail, and then have to undo tagging and redo it.
[TODO or N/A]

Dry run publish release/ branches

---

.github/workflows/rust.yml

Change the branch of workplace publish dry run action to `main`.
I accidentally merged a PR that had the branch set to a temporary branch I was using for testing.

Fix branch of workplace publish dry run action

---

Cargo.lock
Cargo.toml
soroban-env-common/Cargo.toml
soroban-env-common/src/lib.rs
soroban-env-common/src/raw_val.rs
soroban-env-common/src/val_wrapper.rs
soroban-env-common/src/vmcaller_checked_env.rs
soroban-env-host/Cargo.toml
soroban-env-host/src/events.rs
soroban-env-host/src/host.rs
soroban-env-host/src/test/budget_metering.rs
soroban-env-host/src/test/bytes.rs
soroban-env-host/src/vm.rs
soroban-env-host/src/vm/dispatch.rs
soroban-env-host/src/vm/func_info.rs
soroban-test-wasms/wasm-workspace/Cargo.toml

This upgrades the env crates to use the new wasmi_v1 API that arrives with [the upgrade to wasmi 0.16.0](https://github.com/stellar/wasmi/pull/2).
Unfortunately it's quite invasive: every host function signature changes inside the host. The fallout _should_ be limited to the host (and people who embed and invoke it). Most of the changes have to do with the fact that wasmi now requires us to thread a `&mut Store` through to the host function if we want to use anything stored _in_ its store (such as linear memory). We can't dynamically acquire mutable access to it elsewhere, as it's already mutably borrowed during execution.
Everything else is mostly just "same task, different API" sort of stuff. Module parsing and dispatch functions actually got a little simpler.

Migrate to wasmi_v1 API

---

soroban-env-common/src/lib.rs
soroban-env-common/src/status.rs
soroban-env-host/src/host.rs
soroban-env-host/src/test/contract_event.rs
soroban-env-host/src/test/map.rs

Move the OK, UNKNOWN_ERROR consts into Symbol.
The constants are presented without context in the exported API of the soroban-env-* crates. Code without context is easily misunderstood, or maybe more accurately put, more difficult to understand. Moving the consts into the Symbol type gives them the perfect context because their values are of type Symbol. This improves the ergonomics of using the OK error type in contracts.

Move the OK, UNKNOWN_ERROR consts into Symbol

---

soroban-env-common/src/lib.rs
soroban-env-common/src/result.rs

Add RawVal conversions for Result<>
For use in contracts that want to return a result or an error that can be handled. Similar to Ethereum contracts where developers return enums for error conditions.
Note that there are no tests in this PR, because it is much easier and more meaningful to test this logic in the SDK. This logic would probably live in the SDK if not for the limitations on where Rust trait implementations are allowed to live.

Add RawVal conversions for Result<>

---

soroban-env-common/src/env_val.rs

Add ScVal -> RawVal conversion without ref.
The ref version was implemented but not the non-ref version.

Add ScVal -> RawVal conversion without ref

---

soroban-env-common/src/result.rs

Fix names of variants in Result conversion to RawVal.
The names Ok and Err match the variant arms of the Rust Result, which is what I should have used for consistency with how UDT enums are encoded.

Fix names of variants in Result conversion to RawVal

---

soroban-env-common/src/lib.rs
soroban-env-common/src/str.rs
soroban-env-host/src/test.rs
soroban-env-host/src/test/str.rs

Add RawVal <> String conversions when the std feature is enabled.
For use in tests for conveniently converting strings to and from `Bytes`.
It's a little unclear on how useful this is, so I might come back and remove it, but I have one use case in some SDK testutils code where it helps simplify SDK code.

Add RawVal <> String conversions for tests

---

soroban-env-host/src/events.rs
soroban-env-host/src/host.rs
soroban-env-host/src/test/invocation.rs

When we transitioned to having format strings in debug events, we didn't purge (or fix to have format-string placeholders) all cases where we were passing a combination of static strings and rawval args. This meant (among other things) that `log_value` always just logs the word `log` -- not exactly useful.

Remove legacy placeholder-free "format strings" on debug events that mask arguments

---

soroban-env-common/src/result.rs
soroban-env-common/src/status.rs

Change the encoding of `Result` to only support conversion to `RawVal` when the error value is `Into<Status>`.
Errors are distinct values that always map to `Status`.
@graydon has plans in the works where when `Status` values are returned from functions it will cause a revert/rollback. So it's important that we only use `Status` or values that convert into `Status` as errors, otherwise it will be confusing if some errors rollback and some do not.
Close https://github.com/stellar/rs-soroban-sdk/issues/631

Change the encoding of Result to only support Status as errpr

---

soroban-env-host/src/host.rs
soroban-env-host/src/test/contract_event.rs
soroban-env-host/src/test/lifecycle.rs

Promote a status return to an error when returning from a frame'd function, thereby causing rollback.

interpret status-return as an error and roll back frame, fix #453

---

soroban-env-host/src/native_contract/token/contract.rs

- Properly sign the args
- Properly spend classic amount (signs were flipped)
Bug fixes, getting this fixed while I continue working on tests.
N/A

Fixes to built-in token `to_smart`\`to_classic` methods

---

soroban-env-host/src/host.rs

This will let users test `LedgerInfo` changes by only updating what they want. Relevant discord thread - https://discord.com/channels/897514728459468821/1022583901115383900.
Related SDK change - https://github.com/stellar/rs-soroban-env/pull/467
[This issue](https://github.com/stellar/soroban-example-dapp/issues/15) can also be resolved with this change easily.

Add with_mutable_ledger_info

---

soroban-test-wasms/wasm-workspace/Cargo.toml

Update soroban-spec dep to the latest main dep, replacing the existing version which is not on the main branch.
The current version was added temporarily as part of dealing with the circular references that the test wasms has on the SDK. Now that the SDK change is merged we can update it here too.

Update soroban-spec dep

---

soroban-env-common/src/env.rs

Add docs for the create_contract_from_source_account host fn.
We should have docs on host functions.

Add docs for the create_contract_from_source_account host fn

---

soroban-env-host/src/host.rs
soroban-env-host/src/host/data_helper.rs
soroban-env-host/src/test/lifecycle.rs

Rename `Host::visit_storage` to `Host::with_mut_storage`. Add `Host::with_storage`. Make these functions and `Host::with_mut_ledger_info` pub.
The broad reason for this change is so that these functions are consistently named, and accessible to the SDK for building out test utilities in the SDK.
We have a mix of `visit_` and `with_` functions, but they're behavior is the same. I asked @graydon what the most idiomatic would be, and he said `with_` was more common in Rust so I went with that.
The storage function provides a mutable value, and in the ledger info we have a mutable variant, so I named it to match.
All these functions have been made public so the SDK can access them, and because there's little reason for them to be private. For example, the `with_mut_ledger_info` was private …

Organize with_mut_storage, with_ledger_info

---

soroban-env-common/src/env_val.rs

Add ScVal try_into_val RawVal.
Convenience. The TryFromVal exists, but not the TryIntoVal for the same direction.

Add ScVal try_into_val RawVal

---

soroban-env-host/benches/common/cost_types/bigint_div_rem.rs
soroban-env-host/benches/common/cost_types/compute_ed25519_pubkey.rs
soroban-env-host/benches/common/cost_types/compute_sha256_hash.rs
soroban-env-host/benches/common/cost_types/ed25519_scalar_mul.rs
soroban-env-host/benches/common/cost_types/host_obj_alloc_slot.rs
soroban-env-host/benches/common/cost_types/im_map_immut_entry.rs
soroban-env-host/benches/common/cost_types/im_map_mut_entry.rs
soroban-env-host/benches/common/cost_types/im_vec_immut_entry.rs
soroban-env-host/benches/common/cost_types/im_vec_mut_entry.rs
soroban-env-host/benches/common/cost_types/im_vec_new.rs
soroban-env-host/benches/common/cost_types/mod.rs
soroban-env-host/benches/common/cost_types/scmap_to_host_map.rs
soroban-env-host/benches/common/cost_types/scvec_to_host_vec.rs
soroban-env-host/benches/common/cost_types/util.rs
soroban-env-host/benches/common/cost_types/verify_ed25519_sig.rs
soroban-env-host/benches/common/cost_types/vm_instantiation.rs
soroban-env-host/benches/common/cost_types/wasm_insn_exec.rs
soroban-env-host/benches/common/measure.rs
soroban-env-host/src/budget.rs
soroban-env-host/src/host.rs

This does a bit of refactoring, commenting and correcting calibration routines. It also adds the ability to run a single calibration benchmark by name by passing it on the command line.

Correct / tidy up / comment calibration code.

---

soroban-env-common/src/status.rs

Add conversion from Status->ScStatus for the ContractError variant.
Contract error is a valid variant, but a Status with that value will result in an XDR invalid error because it is missing from this mapping.

Add missing conversion from Status->ScStatus for the ContractError variant

---

.github/workflows/rust.yml

Use stellar/binaries for binary installs.
To avoid rebuilding tools.

Use stellar/binaries for binary installs

---

soroban-env-host/src/host.rs
soroban-env-host/src/host/metered_map.rs
soroban-env-host/src/storage.rs
soroban-env-host/src/test/account.rs
soroban-env-host/src/test/bytes.rs
soroban-env-host/src/test/map.rs
soroban-env-host/src/test/util.rs

First things first: this _only_ applies to debug builds. In opt builds you can build gigantic maps with no stack overflows (run the included-but-marked-as-`ignore` tests with `cargo test --release unittests -- --include-ignored`).
However, users get a _debug_ build of the host when they run contract unit tests in native local testing mode, and they can (apparently have in the wild) done things that produce large maps in those tests, and that can produce stack overflows and process aborts. Bad experience.
What goes wrong?
The insert path of `im` allocates a handful of interior B-tree nodes "by value" / as local variables held on the stack while it's rebalancing its B-tree. Interior B-tree nodes are fixed-size arrays of 64 copies of a (key,val) entry, and for maps storing `LedgerKey` and …

Bug 554 - fix stack overflow

---

Cargo.lock
Cargo.toml
soroban-env-common/Cargo.toml
soroban-env-macros/Cargo.toml

Change stellar-xdr that was on one package to match stellar-xdr on all other packages. Updated workspace toml to use workspace dependencies.
The use of stellar-xdr should be consistent across all these crates. Unlikely nothing bad will happen in this case, but it's good practice I think to avoid surprises. Also, the stellar-xdr crate is huge, and having to build 2x of the crate on every build is time consuming.
The use of workspace dependencies is new in Rust 1.64, and it allows us to define a version in one place for all crates. This will prevent this same problem from happening.

Fix loan stellar-xdr 0.0.6 version stuck in the past

---

soroban-env-host/src/host.rs

Add Host::with_artificial_test_contract_frame that executes a function inside a test frame artificially created that may not reference a contract that is actually deployed.
To support the SDK providing functionality where logic is executed as a contract, without the contract having to provide that logic itself. This is helpful in testing.
For https://github.com/stellar/rs-soroban-sdk/pull/761
Close https://github.com/stellar/rs-soroban-sdk/issues/739

Add Host::with_artificial_test_contract_frame

---

soroban-env-host/src/budget.rs

Temporary workaround for https://github.com/stellar/rs-soroban-env/issues/579 by disabling budget costs for object cmp. 
[TODO or N/A]

Disable budget costs for object cmp

---

soroban-env-common/Cargo.toml

Loosen serde requirement.
It is unnecessarily tight and incompatible with some dependencies in the soroban-cli.

Loosen serde requirement

---

Cargo.lock
Cargo.toml

Bump version to v0.0.10.
Doing this manually because cargo-workspaces is broken.

Bump version to v0.0.10

---

Cargo.lock
soroban-env-common/Cargo.toml
soroban-test-wasms/wasm-workspace/Cargo.lock

Upgrade crate-git-revision to 0.0.4
Per https://github.com/stellar/crate-git-revision/pull/9, when used as a git dependency, crate-git-revision 0.0.3 fails to find the correct git directory for soroban-common-env, causing the crate to always be rebuilt.
This upgrade fixes the issue, which I have verified manually.
The lockfiles here end up with multiple copies of crate-git-revision.

Upgrade crate-git-revision to 0.0.4

---

soroban-env-common/src/bitset.rs
soroban-env-common/src/compare.rs
soroban-env-common/src/env_val.rs
soroban-env-common/src/lib.rs
soroban-env-common/src/object.rs
soroban-env-common/src/raw_val.rs
soroban-env-common/src/static.rs
soroban-env-common/src/status.rs
soroban-env-common/src/symbol.rs
soroban-env-common/src/tuple.rs
soroban-env-common/src/val_wrapper.rs
soroban-env-host/benches/common/cost_types/im_map_ops.rs
soroban-env-host/benches/common/cost_types/im_vec_ops.rs
soroban-env-host/benches/common/cost_types/record_debug_event.rs
soroban-env-host/benches/common/cost_types/scmap_to_host_map.rs
soroban-env-host/benches/common/cost_types/wasm_insn_exec.rs
soroban-env-host/benches/common/util.rs
soroban-env-host/src/host/comparison.rs
soroban-env-host/src/host/data_helper.rs
soroban-env-host/src/host/metered_map.rs
soroban-env-host/src/native_contract/base_types.rs
soroban-env-host/src/native_contract/invoker.rs
soroban-env-host/src/native_contract/token/admin.rs
soroban-env-host/src/native_contract/token/contract.rs
soroban-env-host/src/native_contract/token/public_types.rs
soroban-env-host/src/storage.rs
soroban-env-host/src/test/map.rs
soroban-env-host/src/test/vec.rs
soroban-env-host/tests/integration.rs
soroban-native-sdk-macros/src/derive_type.rs

To rebase and merge the `EnvVal` removal part of https://github.com/stellar/rs-soroban-env/pull/600. 
See https://github.com/stellar/rs-soroban-env/pull/600#issue-1481017527 for description
At @graydon 's suggestion to split out the `EnvVal` removal part of https://github.com/stellar/rs-soroban-env/pull/600 and merge it first, since it is mostly just clean up and is self-contained. 
It makes the code base much cleaner. 
[TODO or N/A]

Remove `EnvVal`

---

soroban-env-host/src/host.rs
soroban-env-host/src/host/metered_vector.rs

Fix the bug in examples discovered earlier by @sisuresh, by using deep object comparisons in host vector's `first/last_index_of` functions
`HostVec` contains `RawVal`s which may be objects of the identical in content have different object handles, thus deep comparison is needed. 
[TODO or N/A]

Fix `first/last_index_of` functions to use deep object comparison

---

soroban-env-host/src/native_contract/token/balance.rs
soroban-env-host/src/native_contract/token/storage_types.rs
soroban-env-host/src/test/token.rs

This is based off of an earlier [prototype](https://github.com/stellar/rs-soroban-env/pull/578). The goal of this change is to enforce auth_required on non-account balances. The admin will need to authorize users before they can hold a balance.

Add auth_required support for non-account balances

---

soroban-env-common/src/array.rs
soroban-env-common/src/convert.rs
soroban-env-common/src/env_val.rs
soroban-env-common/src/lib.rs
soroban-env-common/src/object.rs
soroban-env-common/src/option.rs
soroban-env-common/src/raw_val.rs
soroban-env-common/src/result.rs
soroban-env-common/src/str.rs
soroban-env-common/src/tuple.rs
soroban-env-common/src/val_wrapper.rs
soroban-env-host/src/host.rs
soroban-env-host/src/native_contract/base_types.rs
soroban-env-host/src/native_contract/invoker.rs
soroban-env-host/src/native_contract/testutils.rs
soroban-env-host/src/native_contract/token/admin.rs
soroban-env-host/src/native_contract/token/contract.rs
soroban-env-host/src/native_contract/token/cryptography.rs
soroban-env-host/src/native_contract/token/event.rs
soroban-env-host/src/native_contract/token/metadata.rs
soroban-env-host/src/native_contract/token/test_token.rs
soroban-env-host/src/test/basic.rs
soroban-env-host/src/test/token.rs
soroban-env-host/src/test/tuple.rs
soroban-env-host/tests/option.rs
soroban-native-sdk-macros/src/derive_type.rs

This is a "minimal" version of the change I've been attempting to make to `TryFromVal` and friends for the past few weeks.
It defers mucking with the error types to a later PR (I have an idea for how to do that but it doesn't _have_ to happen here). The minimal changes here are just to get rid of so many impls to improve maintainability -- net removal of about 300 lines -- while expanding and systematizing overall coverage (the error stuff will also make things a bit more systematic).
The changes here are:
- Remove non-Try {Into,From}Val. 
- Blanket-impl TryIntoVal to use TryFromVal, removing all manual TryIntoVal impls.
- Switch TryFromVal to take &T everywhere, removing the T-vs-&T duplication.
It seems to hold together, so I'm going to start on the SDK changes to match. Feedback …

Reform TryFromVal to reduce number of impls.

---

soroban-env-host/src/auth.rs
soroban-env-host/src/host.rs
soroban-env-host/src/native_contract/token/contract.rs

This helps recording preflights to provide the correct footprint for simple cases.
Improving preflight UX
It's not possible to test this with the built-in token (as we need the account entries for the test setup), so leaving the tests for the followup.
This is very simplistic and should be eventually expanded to use mock signatures and actually run the auth code.

Emulate classic account authentication in recording auth mode.

---

soroban-env-host/src/auth.rs
soroban-env-host/src/host.rs
soroban-env-host/src/test/token.rs

Change the auth testing to return all the top-level recordings instead of polling auth manager for their presence.
Also did a passing-by cleanup of the invoker logic in recording mode to ensure we always record the address and only replace it with none in the preflight payloads.
Improve testing UX
I'm not introducing the function to return the full tree for now as it's not critical for the first release and the tree representation would be a bit tricky. We can add this as a followup later.

Change the interface for the auth testing utility.

---

soroban-env-host/src/budget.rs

This PR removes the `#[cfg(test)]` guard before the `reset_limits` function for the budget implementation.
This PR will close #666 
This change allows the definition of a custom budget outside of the already given "unlimited" and "standard" variants.
In the current state this change should not have any downsides. On the long run this will most likely need to change when coming to a consent about production level budgeting.

Allow for a custom budget outside tests

---

soroban-env-host/src/auth.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/data_helper.rs
soroban-env-host/src/test/invocation.rs

- The account now returns an option and it's up to the client to return an error.
- Use `ok_or_else` instead of `ok_or`
Remove confusing error messages that don't mean anything.
N/A

Remove the unnecessary error events that appeared in non-error scenarios

---

soroban-env-host/src/budget.rs
soroban-env-host/src/events/internal.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/metered_clone.rs
soroban-env-host/src/host/metered_map.rs
soroban-env-host/src/host/metered_vector.rs
soroban-env-host/src/test/budget_metering.rs
soroban-env-host/src/test/event.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/604 and https://github.com/stellar/rs-soroban-env/issues/680.
This PR reforms `metered_clone`.
- Splits memory allocation from shallow copying
- Define the "shallow size" of `MeteredClone` types. 
A `metered_clone` consist of shallow copying of the type's memory footprint (for a `Vec` it's 24), plus recursively (deep) cloning any of the substructures. 
A `HostMemAlloc` charge occurs only when memory is allocated. I.e. types involving `alloc` -- `Box`, `Vec`, `Rc` etc.
The shallow copying of a type is charged the amount `ELT_SIZE` defined by the implementer, and there is a runtime check to ensure that amount is the upper bound of the actual memory size of the type `mem::size_of<T>`.
Adds a test in `budget_metering.rs` to demonstrate …

Reform metering for value cloning and memory allocation

---

soroban-env-host/src/host.rs

This just fixes a small mistake in vec_new_from_linear_memory that unfortunately turns it into a no-op. Cause of https://github.com/stellar/soroban-tools/pull/494#issuecomment-1466513951

fix thinko in vec_new_from_linear_memory

---

soroban-env-common/src/env_val.rs
soroban-env-common/src/num.rs
soroban-env-host/src/test/num.rs

Fix a missing-sign-extension bug in i128 conversion to u64 payloads (which is, of course, exactly the type of bug I was worried I'd write if we used _signed_ payloads; sigh, there is no avoiding this bug class)

Fix an i128 conversion bug

---

soroban-env-host/src/budget.rs

Increase memory budget to 50MB
And add impl to std::fmt::Display, make the alignment nicer.
In the current set up with 40M insns and 10M bytes limit, the memory limit will be reached first in most scenarios. 
The cost for `VmInstantiation` is 1M cpu insns and 1.2M mem bytes (both are constant costs per input), and this is by far the biggest cost for most contracts. 
For a contract making 10 cross contract calls, the memory limit will run out while the cpu limit has plenty left.
Increasing `mem_bytes` to 50MB ensures both resource usages has enough room to grow, and memory limit doesn't become the bottleneck. 
[TODO or N/A]

Increase memory budget to 50MB

---

soroban-env-host/src/native_contract/token/admin.rs
soroban-env-host/src/native_contract/token/contract.rs
soroban-env-host/src/native_contract/token/test_token.rs
soroban-env-host/src/test/token.rs

Remove `admin` argument from the token admin interface.
Instead simply require auth for the stored admin address.
Simplify/reduce the interface.
N/A

Remove `admin` argument from the token admin interface.

---

soroban-env-common/src/status.rs
soroban-env-host/src/host/comparison.rs

Three patches toward making `Compare<RawVal> for Env` and `Compare<ScVal> for Budget` behave identically to `Ord for ScVal`, per https://github.com/stellar/rs-soroban-env/issues/743.
These are the initial patches described in my comment here: https://github.com/stellar/rs-soroban-env/issues/743#issuecomment-1496661230
As discussed in that issue, all three of `Compare<RawVal> for Env`, `Compare<ScVal> for Budget` and `Ord for ScVal` need to behave the same. These patches fix the first three discrepancies I have found through fuzzing.
This adds some hand-written unit tests to prevent regressions, but I intend to add comprehensive proptests / fuzz tests to the soroban-sdk crate eventually. Such tests depend on some fuzzing-related patches that are not yet ready to land.

Comparison fixes

---

soroban-env-host/src/host.rs
soroban-env-host/src/lib.rs

This adds a new mechanism for gating old behaviour in the host. Currently it's not used, but the idea is that as we discover divergence we will need to add branches to the code here and there to run "as if" we were an old version.
This is _similar_ to the way protocol-version (and occasionally ledger-number) gating of backward-compatibility code happens in stellar-core, except that (a) ledger-number gating is both brittle and uninformative and (b) we don't have clear enough insight _in advance_ of making a breaking change that we're doing so, due to the size of the dependency tree. So instead the embedder is forced to do a multi-step upgrade process, with two versions of the entire host active at once. The embedder _should_ be able to do this correctly since it both sees the entire …

Add soroban_env_host::host::LegacyEpoch

---

soroban-env-common/src/symbol.rs
soroban-env-host/src/host.rs
soroban-env-host/src/test.rs
soroban-env-host/src/test/symbol.rs

Validate that large Symbol values do not contain chars that are not allowed in Symbol types.
The conversion from str to Symbol falls back to the object path if a SymbolSmall cannot be created. The Host::symbol_new_from_slice function though does not do the required validation:
```rust
impl<E: Env> TryFromVal<E, &str> for Symbol {
type Error = ConversionError;
fn try_from_val(env: &E, v: &&str) -> Result<Self, Self::Error> {
if let Ok(ss) = SymbolSmall::try_from_str(v) {
Ok(Self(ss.0))
} else if let Ok(so) = env.symbol_new_from_slice(v) {
Ok(Self(so.0))
} else {
Err(ConversionError)
}
}
}
```
Symbol::new_from_slice creates an `ScSymbol` and puts it into the environment, but ScSymbol is (currently) allowed to contain invalid chars:
```rust
fn symbol_new_from_slice(&self, s: &str) -> …
```

Don't allow invalid chars in Symbol objects.

---

soroban-env-host/src/host.rs

Undo pub(crate)ing of set_authorization_entries function in host.
I'm using it in the SDK in a PR I'm working on. It was just marked as pub crate in https://github.com/stellar/rs-soroban-env/commit/dab3fd1a813e2bf5c6b23cd828d46de11f40b442 today, but it doesn't appear to be critical to that change. I'd like to keep it public for use in the SDK. The SDK needs to be able to set authorization entries independent of invoking a host function since the SDK does invocations via the Env call interface.

Undo pub(crate)ing of fn in host

---

soroban-env-host/src/auth.rs

Remove redundant `clone` calls in auth manager
Optimization
N/A

Remove redundant `clone` calls

---

.github/workflows/rust.yml
Cargo.lock
deny.toml
soroban-env-host/Cargo.toml
soroban-env-host/src/host/metered_xdr.rs
soroban-env-host/src/test/lifecycle.rs

This adds support for `cargo-deny` which enforces a few sets of checks:
- Acceptable licenses in dependencies
- Absence of known security advisories
- Absence of yanked or unmaintained crates
- Absence of multiple duplicated versions of crates
- Absence of crates from unknown sources
I've fixed the warnings it flagged on our current codebase (a couple yanks and a duplication that needs a roll back) and added a github action to run it. Probably some fine-tuning will be required, but it's a start. There's some mess in the dalek dependency tree that should be fixed soon when dalek finalizes v2.0.

Initial configuration of cargo-deny.

---

soroban-env-host/src/fees.rs
soroban-env-host/src/lib.rs
soroban-env-host/tests/fees.rs

Add a library for the fee computation to the host.
While this is not strictly a part of the host, it is shared between the host users, hence it makes sense to distribute these together.
This will be used both in Stellar core and in Soroban RPC for the fee computations.
N/A

Add a library for the fee computation to the host.

---

.github/workflows/rust.yml

This just changes the matrix back to the way it was in the upstream example, running the advisories check (which is somewhat out of our control -- advisories come out asynchronously) separately from the other 3 checks which are in our control.

Fix the cargo-deny matrix in rust.yml

---

Cargo.toml
soroban-env-common/Cargo.toml
soroban-env-common/src/raw_val.rs
soroban-env-common/src/vmcaller_env.rs
soroban-env-common/src/wrapper_macros.rs
soroban-env-host/Cargo.toml
soroban-env-host/src/auth.rs
soroban-env-host/src/cost_runner/cost_types/mod.rs
soroban-env-host/src/events/debug.rs
soroban-env-host/src/events/diagnostic.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/frame.rs
soroban-env-host/src/host/mem_helper.rs
soroban-env-host/src/lib.rs
soroban-env-host/src/test.rs
soroban-env-host/src/test/bytes.rs
soroban-env-host/src/test/storage.rs
soroban-env-host/src/test/token.rs

This removes all features from the host besides `testutils`
- The `"serde"` feature was unused
- The `"hostfn_log_fmt_values"` feature was an over-conservative setting that didn't need to be static; we already have a dynamic flag `is_debug()` that uses the dynamic diagnostic level to enable expensive logging, we should just use that
- The `"vm"` feature was there to theoretically support building a native testing config of the host without any VM -- for testing purely native contracts -- but in practice testing always builds with `"vm"` enabled and users test a mix of native and wasm contracts, so there's just no use for it.
There's no functional change here, just simplification of the codebase (and speeding-up of test cycles).

Anti features

---

Cargo.lock
soroban-env-host/Cargo.toml
soroban-env-host/src/events/diagnostic.rs
soroban-env-host/src/events/internal.rs
soroban-env-host/src/events/mod.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/error.rs
soroban-env-host/src/host/frame.rs
soroban-env-host/src/host/metered_clone.rs
soroban-env-host/src/test/event.rs
soroban-env-host/src/test/invocation.rs
soroban-env-host/src/test/lifecycle.rs
soroban-env-host/src/vm.rs
soroban-env-host/tests/integration.rs

A small set of residual cleanups noticed after the giant error change yesterday
1. Removing the dynamic formatting string stuff and tinyvec (no longer used)
2. Renaming functions and types for clarity and lack of redundancy
3. Allowing mixing host and xdr objects in topic and data so there's a place to put pre-formed `Hash` values
4. Splitting cases of `debug` diagnostics (redundant and meaningless) into specifically `log` or `error` cases
5. Fixing some typos and whitespace formatting in diagnostic messages

Some further cleanups to diagnostic events

---

soroban-env-host/src/auth.rs
soroban-env-host/src/test/token.rs

Change authentication contract errors to be auth errors.
Returning contract errors introduces undesired confusion in terms of which entity has produced the error: https://github.com/stellar/rs-soroban-env/issues/771
N/A

Change authentication contract errors to be auth errors.

---

soroban-env-host/benches/common/cost_types/wasm_insn_exec.rs
soroban-env-host/benches/common/measure.rs
soroban-env-host/benches/common/mod.rs
soroban-env-host/benches/common/util.rs
soroban-env-host/benches/worst_case_linear_models.rs
soroban-env-host/src/budget.rs
soroban-env-host/src/cost_runner/cost_types/wasm_insn_exec.rs
soroban-env-host/src/test/budget_metering.rs
soroban-env-host/src/vm.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/610
- Adapts to the new Wasmi
- Add Wasm instruction tiers and generate tiered calibration
- Extract the base fuel cost and the ratios between tiers (used for `FuelCost` config for Wasmi)
- Misc. clean ups and improvements: 
- remove `WasmInsnExec`, the single-tiered calibration of a mix-bag of sample wasm insns.
- remove `WasmMemAlloc`, no longer needed.
- document the difference between trapping and passing baseline measurements. Converted some from passing to trapping.
- Updated cost parameters based on [output](https://github.com/stellar/rs-soroban-env/files/11703796/output21.txt)
[TODO or …

Calibrate wasmi fuel and tiered wasm instructions

---

soroban-env-common/src/error.rs

`impl TryFrom<&Error> for ScVal`
`Error` cannot be stored in `#[contracttype]`s.
This impl is required for types to be stored in `#[contracttype]`. Without it the compiler produces errors like
```
error[E0277]: the trait bound `stellar_xdr::ScVal: From<&soroban_env_host::Error>` is not satisfied
--> soroban-sdk/src/arbitrary.rs:1027:9
|
1027 |         #[contracttype]
|         ^^^^^^^^^^^^^^^ the trait `From<&soroban_env_host::Error>` is not implemented for `stellar_xdr::
ScVal`
|
= note: required for `&soroban_env_host::Error` to implement `Into<stellar_xdr::ScVal>`
= note: required for `stellar_xdr::ScVal` to implement `TryFrom<&soroban_env_host::Error>`
= note: required for `&soroban_env_host::Error` to implement `TryInto<stellar_xdr::ScVal>`
= note: this error originates in the …
```

Implement TryFrom<&Error> for ScVal

---

soroban-env-host/src/host/metered_map.rs
soroban-env-host/src/test/budget_metering.rs

We currently only check map order in the `from_map` path, not the `from_exact_iter` path. This fixes it to do both.
Fixed #869

Check map order when rebuilding from exact iter

---

soroban-env-host/src/expiration_ledger_bumps.rs

This is required for core to be able to iterate over the expiration bumps.

Expose bumps

---

soroban-env-host/src/auth.rs

Make `RecordedAuthPayload` consistently return `None` for invoker.
This check has accidentally been removed during refactoring.
Bugfix
N/A

Make `RecordedAuthPayload` consistently return `None` for invoker.

---

soroban-env-host/src/budget.rs
soroban-env-host/src/cost_runner/cost_types/vm_ops.rs
soroban-env-host/src/cost_runner/runner.rs
soroban-env-host/src/events/diagnostic.rs
soroban-env-host/src/events/mod.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/data_helper.rs
soroban-env-host/src/host/error.rs
soroban-env-host/src/host/frame.rs
soroban-env-host/src/host_object.rs
soroban-env-host/src/storage.rs
soroban-env-host/src/test/auth.rs
soroban-env-host/src/test/budget_metering.rs
soroban-env-host/src/test/complex.rs
soroban-env-host/src/test/event.rs
soroban-env-host/src/test/hostile.rs
soroban-env-host/src/test/invocation.rs
soroban-env-host/src/test/ledger.rs
soroban-env-host/src/test/lifecycle.rs
soroban-env-host/src/test/prng.rs
soroban-env-host/src/test/storage.rs
soroban-env-host/src/test/token.rs
soroban-env-host/src/test/util.rs
soroban-env-host/src/vm.rs
soroban-env-host/tests/integration.rs

Fix #817 
I'm still not 100% sure we _want_ this -- a dynamic borrow error usually means there's something structurally wrong with the control pattern calling the function, and this might basically make it "recoverable" in some partial sense where it might be cleaner to panic out to the outermost panic handler -- but in either case if someone triggers one we'll be stuck preserving it for backwards compatibility for all time, and this might be a _little_ easier to preserve?
Anyway, assuming we do, this does it.

Turn dynamic borrow panics into HostErrors

---

soroban-env-host/src/host/crypto.rs

Use Ed25519 verify_strict function rather than just verify, fix #857

---

soroban-env-host/benches/common/cost_types/vec_ops.rs
soroban-env-host/benches/common/measure.rs
soroban-env-host/benches/common/util.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/conversion.rs
soroban-env-host/src/host/mem_helper.rs
soroban-env-host/src/host/metered_map.rs
soroban-env-host/src/host/metered_vector.rs

This just fixes a couple issues that can cause 32 bit hosts to diverge from 64 bit hosts in extreme cases (not likely one could ever hit them due to metering, but whatever). Also explicitly caps size of vectors and maps to u32::max.
Fixes #895

Misc int32 issues

---

soroban-env-host/src/host.rs
soroban-env-host/src/host_object.rs
soroban-env-host/src/test/budget_metering.rs
soroban-env-host/src/test/map.rs
soroban-env-host/src/test/vec.rs

This isn't so much a "safety" issue as a confusion-of-users issue. We want to detect any malformed object handles (bad index, bad tags) as early as possible, so users don't have to diagnose late errors when a lookup finally traps.
Anyway, this makes it impossible to insert a malformed one into a container, and since containers are how you form argument lists to making calls, it implicitly confines malformed object handles to a single contract instance.

Enforce object handle integrity when inserting into containers, fix #569

---

soroban-env-host/src/test/map.rs

Turns out we were already doing #223, so the most I can think to add is "a test of one part we didn't seem to have a test for yet".
Closes #223.

Add testcase for out-of-order scmaps, fix #223.

---

soroban-env-host/src/auth.rs
soroban-env-host/src/test/auth.rs

Prohibit using disjoint signatures to cover the auth tree.
Also did a passing-by cleanup to not load the source account lazily. We should have source account available in relevant contexts that use enforcing auth.
This makes it so require auth calls like A->B can't succeed if signatures for A and B are passed separately. This is achieved via requiring all the authorized calls to belong to some active root higher up the tree (if any).
It is still possible to have multiple disjoint trees on behalf of the same address, but they must have their roots at the same call tree level.
N/A

Prohibit using disjoint signatures to cover the auth tree.

---

Cargo.lock
Cargo.toml
soroban-env-common/src/error.rs
soroban-env-host/benches/common/measure.rs
soroban-env-host/src/budget.rs
soroban-env-host/src/host/metered_map.rs
soroban-env-host/src/host/metered_vector.rs
soroban-env-host/src/test/budget_metering.rs
soroban-env-host/src/test/hostile.rs
soroban-env-host/src/vm.rs
soroban-env-host/src/vm/dispatch.rs
soroban-env-host/src/vm/fuel_refillable.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/896
This is attempt 2. Follows up on https://github.com/stellar/rs-soroban-env/pull/946#pullrequestreview-1530786663
Make the host a `ResourceLimiter`, such that the entire memory budget is available to the Vm linear memory. 
Also hardcodes several other limits as `WASMI_LIMITS_CONFIG`, hopefully we won't need to change them ever. 
This is a superior approach to https://github.com/stellar/rs-soroban-env/pull/946, both in terms of functional (dynamic memory limit) and cleanness (does not require changing the StoreData). 
[TODO or N/A]

Adapt to ResourceLimiter, replacing mem_fuel metering

---

soroban-env-host/src/host.rs
soroban-env-host/src/test/storage.rs

Make `del_contract_data` no-op for removing non-existent instance storage key.
Resolves https://github.com/stellar/rs-soroban-env/issues/949
This was inconsistent with persistent/temp storage, which doesn't return error for non-existent keys.
N/A

Make `del_contract_data` no-op for removing non-existent instance storage key.

---

Cargo.lock
Cargo.toml
soroban-env-common/src/error.rs
soroban-env-common/src/val.rs
soroban-env-host/src/test/bytes.rs

This is the env-side change accompanying https://github.com/stellar/stellar-xdr/pull/125
Fixes https://github.com/stellar/rs-soroban-env/issues/953

Adapt to SCError change to be an enum, with ContractError(u32)

---

Cargo.lock
Cargo.toml
soroban-env-host/src/fees.rs
soroban-env-host/tests/fees.rs

Bump env xdr and do the fee library changes corresponding to config changes
Switching to charging for just events
N/A

Bump env xdr and do the fee library changes corresponding to config changes

---

soroban-env-host/src/cost_runner/cost_types/visit_object.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/comparison.rs
soroban-env-host/src/host/conversion.rs
soroban-env-host/src/host_object.rs

This does three things:
- Sinks the check for unknown object handles into `unchecked_visit_val_obj` (it's currently done in all callers).
- Removes the `unsafe` qualifier, there's really nothing about it that a caller has to think carefully about (and arguably we're misusing `unsafe` for this purpose all through the codebase, I expect nobody appreciates this instance!)
- Renames the function to be a little less hazardous-sounding: `visit_obj_untyped`
This (plus earlier work tightening up its args) addresses anything I had in mind for #595

Tighten signature of unchecked_visit_val_obj, fix #595

---

Cargo.lock
deny.toml
soroban-env-common/Cargo.toml
soroban-env-common/src/val.rs
soroban-env-host/Cargo.toml
soroban-env-macros/Cargo.toml

In the process of updating deps in the SDK to take the dalek change I realized most of the syn2 exemptions are also no longer needed, so I tidied these up in env as well, and also got rid of a few unused deps.

Tighten dependencies further

---

Cargo.lock
Cargo.toml

This will just update the env to take the XDR change that removes SCSpecTypeSet. Will need to adjust it once the XDR actually lands.

Update XDR to take change that removes SCSpecTypeSet

---

soroban-env-common/src/val.rs

Fix comparison in `Tag::is_object`.
This function incorrectly always returns true. The more-commonly-used `Val::is_object` is correct. This patch makes both functions agree.
I would prefer `Val::is_object` delegate to `Tag::is_object`, but that can't be done without constructing a `Tag`, which has several branches, and I take it `Val::is_object` is a fast path.
`Tag::is_object` and `Val::is_object` duplicate code.

Fix comparison in Tag::is_object

---

soroban-env-host/benches/common/cost_types/compute_ed25519_pubkey.rs
soroban-env-host/benches/common/cost_types/verify_ed25519_sig.rs
soroban-env-host/benches/common/cost_types/vm_ops.rs
soroban-env-host/benches/common/measure.rs

Fix calibration due to delak change

---

soroban-env-host/src/fees.rs
soroban-env-host/tests/fees.rs

Charge write fees for expiration entry bumps.
We charge these as a part of the rent fee, so it's effectively an additional flat component of the final rent cost. It's not going to be explicitly exposed or limited.
Rent bumps are not completely free, so fee model needs to reflect that. Also this discourages doing extremely short-termed bumps and thus should reduce the ledger load a bit.
N/A

Charge write fees for expiration entry bumps.

---

soroban-env-host/src/e2e_invoke.rs

Remove key size from rent change computation.
It's not written to the ledger separately and thus shouldn't be accounted for rent.
N/A

Remove key size from rent change computation.

---

Cargo.lock
Cargo.toml

Implementation of [this plan](https://github.com/stellar/stellar-xdr/pull/141#discussion_r1307930385). Needs to not land until the corresponding XDR and rs-XDR lands and its rev is updated.

Take change from txSOROBAN_RESOURCE_LIMIT_EXCEEDED to txSOROBAN_INVALID

---

soroban-env-host/src/e2e_invoke.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/crypto.rs
soroban-env-host/src/host/declared_size.rs
soroban-env-host/src/host/metered_clone.rs

This PR updates the host interface to accept a buffer of ExpirationEntries that line up with the ledger entry buffer. If the ledger entry doesn't have an expiration entry, then the entry will be an empty buffer (not null).

Add ExpirationEntry support

---

soroban-env-host/src/e2e_invoke.rs

Resolves https://github.com/stellar/stellar-core/issues/3902
Previously it calls `metered_collect` with the input being the size of the event buffer. This makes the metering numbers inconsistent when diagnostic events are turned on or off.
Needs more end-to-end testing on diagnostic events to catch future errors like this. https://github.com/stellar/rs-soroban-env/issues/916

Fix encode contract events metering

---

Makefile
soroban-env-host/src/events/diagnostic.rs

This adds a `make coverage` target that you can use to make an `lcov.info` file in your workspace. This in turn can be used directly by the VSCode [coverage gutters extension](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) to display code coverage while editing and/or reviewing code.
It should be a helpful signal for review (and improving coverage).

Add "coverage" Makefile target for lcov.info, add a test that extends coverage

---

soroban-env-host/src/native_contract/base_types.rs
soroban-env-host/src/native_contract/token/metadata.rs

I thought this was just a UI error but the native contract stores this rendering in the database, so it's really a protocol-level correctness issue.
Fixes #1032

Fix asset-code rendering in native contract.

---

soroban-env-common/src/arbitrary.rs
soroban-env-common/src/bytes.rs
soroban-env-common/src/compare.rs
soroban-env-common/src/convert.rs
soroban-env-common/src/env.rs
soroban-env-common/src/error.rs
soroban-env-common/src/result.rs
soroban-env-common/src/storage_type.rs
soroban-env-common/src/string.rs
soroban-env-common/src/symbol.rs
soroban-env-common/src/tuple.rs
soroban-env-common/src/val.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/error.rs
soroban-native-sdk-macros/src/derive_type.rs

Steps in code review so far:
- Rename some variables
- Move code around for ease of review, add review markers
- Equip `Env::Error` with `: Into<crate::Error>` so that we can pass `HostError::error` through from Env conversions
- Do so in bytes.rs
- Equip `Env::Error` with `: From<crate::Error>` so that we can project `Error` into it in certain cases
- Do so in preference to an unconditional `unreachable!()` in convert, which can panic
- Fix some code in convert that does two compares back to back when walking a tuple instead of scrutinizing one compare against two cases
- Change a bunch more uses of ConversionError to Error (some need minor SDK changes, see https://github.com/stellar/rs-soroban-sdk/pull/1083)

Graydon code review

---

soroban-env-common/src/meta.rs
soroban-env-host/src/host.rs
soroban-env-host/src/test/complex.rs
soroban-env-host/src/test/hostile.rs
soroban-env-host/src/test/invocation.rs
soroban-env-host/src/test/ledger.rs
soroban-env-host/src/test/lifecycle.rs
soroban-env-host/src/test/metering_benchmark.rs
soroban-env-host/src/test/token.rs
soroban-env-host/src/test/util.rs
soroban-env-host/src/vm.rs

This fixes #1052 by rejecting contracts with unsupported versions during upload (they are already rejected during instantiation/execution). It also slightly tightens the set of allowed contracts, rejecting old-protocol ones with nonzero prerelease and rejecting all future protocol versions.

Tighten wasm interface version checks, and do on upload. Fix #1052.

---

Cargo.lock
Cargo.toml

Update wasmi dependency to https://github.com/stellar/wasmi/tree/soroban-wasmi-v0.31
[TODO or N/A]

Update wasmi to 0.31.0-soroban

---

soroban-env-common/src/symbol.rs
soroban-env-host/src/host.rs

In general this is not a correct adjustment to make in symbol_copy_to_slice because that function takes an arbitrary input pos in the symbol it's copying from (like all the buffer-copy host functions). It is correct only in the case where pos == 0 and even then it represents a bit of a footgun by papering over real errors in the caller (passing too long a slice, which the caller might incorrectly assume is entirely filled by the call if the call silently succeeded).
This adjustment was added in 0bc40291ae38f63a7e8c5521297e42ce77fd6c85 presumably in order to "make tests pass". Removing it does break tests but only because of one call path that uses this host function, where a host SymbolObject is converted to a fixed-length guest SymbolStr. This is a caller in which a zero pos is already …

Move out-slice len adjustment from symbol_copy_to_slice to its caller.

---

soroban-env-host/src/host/metered_map.rs

Remove metered map iterator functions.
These aren't used/needed anymore.
N/A

Remove metered map iterator functions.

---

soroban-env-host/src/auth.rs

Attach the auth in recording mode to any valid tracker when possible.
Currently only the tracker that matches with exact same object is used and otherwise a new tracker is created. This results in recording auth producing unnecessarily disjoint call trees.
This is kind of best effort and might lead to a bit weird edge-case scenarios in semantic sense (e.g. a tracker for an exact address object might be used by another instance of that address), but the end results should still fulfil the enforcing mode invariants and shouldn't compromise security.
N/A

Attach the auth in recording mode to any valid tracker when possible.

---

soroban-env-common/Cargo.toml
soroban-env-host/Cargo.toml

Some crates have not exhaustively listed all its "feature=next" dependencies. 
Even if some of those "next" are redundant, i.e., they may only underneath differ by `stellar-xdr`'s `curr/next`, which is already covered by `soroban-env-common`. I think it's still good to list them out explicitly, since it's possible those dependencies may have more divergence between their curr and next in the future.
[TODO or N/A]

Add redundant "next" dependencies

---

soroban-env-host/src/auth.rs

Use Address for `call_account_contract_check_auth` test helper.
This is one of the functions that has been overlooked during Bytes->Address migration. This is also needed to support https://github.com/stellar/rs-soroban-sdk/pull/1112
N/A

Use Address for `call_account_contract_check_auth` test helper.

---

Cargo.lock
soroban-bench-utils/src/tracker.rs
soroban-env-common/Cargo.toml
soroban-env-common/src/lib.rs
soroban-env-common/src/vmcaller_env.rs
soroban-env-host/Cargo.toml
soroban-env-host/benches/common/cost_types/host_mem_cpy.rs
soroban-env-host/benches/common/measure.rs
soroban-env-host/benches/variation_histograms.rs
soroban-env-host/benches/worst_case_linear_models.rs
soroban-env-host/src/budget.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/mem_helper.rs
soroban-env-host/src/test/budget_metering.rs
soroban-env-host/src/test/metering_benchmark.rs
soroban-env-host/src/test/util.rs
soroban-env-host/src/vm.rs
soroban-env-host/src/vm/dispatch.rs

A bunch of exploration of minor issues discovered in budget calibration, ostensibly about #1020 but also involving some tracy markup, some internal cleanup, machinery to allow excluding the overwhelming VM instantiation cost center, and some attempts at setting budget costs more from first principles.

Budget fiddling

---

soroban-env-host/src/fees.rs
soroban-env-host/src/host/crypto.rs
soroban-env-host/src/host/prng.rs
soroban-env-host/src/vm/dispatch.rs

Nothing critical here, just some defensive arithmetic and a few edge cases that I wasn't sure about in fees (possibly a bug? I wasn't sure in conversation with @dmkozh but in any case refactored for readability), plus one real pub-to-pub(crate) in crypto and one in prng.

Code review on fees, crypto, prng, dispatch

---

soroban-env-host/src/storage.rs

This is the one change I'm fairly confident ought to happen in storage: factoring the `get` paths into a common funnel. Besides being duplicate code, if you look carefully the previous arrangement had inconsistent handling of `None` returns from the underlying map too: one path (correctly) treated it as an internal error since `prepare_read_only_access` shouldn't allow getting there; the other two paths either returned it as-is or merged it into the `MissingValue` path.
I'm not changing two other error codes just yet, though I was a bit tempted to. Would be interested to hear input from @dmkozh : as mentioned in conversation elsewhere, I _think_ the footprint checking paths should probably return `InvalidAction` as errors rather than `ExceededLimit`; and possibly the path in `extend` that …

storage code review

---

Cargo.lock
soroban-env-host/Cargo.toml
soroban-env-host/benches/common/experimental/ed25519_scalar_mul.rs
soroban-env-host/benches/common/experimental/mod.rs
soroban-env-host/benches/common/measure.rs
soroban-env-host/benches/common/mod.rs
soroban-env-host/benches/variation_histograms.rs
soroban-env-host/benches/worst_case_linear_models.rs
soroban-env-host/src/cost_runner/cost_types/compute_ecdsa_secp256k1_sig.rs
soroban-env-host/src/cost_runner/cost_types/compute_ed25519_pubkey.rs
soroban-env-host/src/cost_runner/cost_types/compute_keccak256_hash.rs
soroban-env-host/src/cost_runner/cost_types/compute_sha256_hash.rs
soroban-env-host/src/cost_runner/cost_types/host_mem_alloc.rs
soroban-env-host/src/cost_runner/cost_types/host_mem_cmp.rs
soroban-env-host/src/cost_runner/cost_types/host_mem_cpy.rs
soroban-env-host/src/cost_runner/cost_types/invoke.rs
soroban-env-host/src/cost_runner/cost_types/num_ops.rs
soroban-env-host/src/cost_runner/cost_types/prng.rs
soroban-env-host/src/cost_runner/cost_types/recover_ecdsa_secp256k1_key.rs
soroban-env-host/src/cost_runner/cost_types/val_deser.rs
soroban-env-host/src/cost_runner/cost_types/val_ser.rs
soroban-env-host/src/cost_runner/cost_types/verify_ed25519_sig.rs
soroban-env-host/src/cost_runner/cost_types/visit_object.rs
soroban-env-host/src/cost_runner/cost_types/vm_ops.rs
soroban-env-host/src/cost_runner/cost_types/wasm_insn_exec.rs
soroban-env-host/src/cost_runner/experimental/ed25519_scalar_mut.rs
soroban-env-host/src/cost_runner/experimental/mod.rs
soroban-env-host/src/cost_runner/mod.rs
soroban-env-host/src/cost_runner/runner.rs

Setup bench framework to run experiments 
- Experimental bench code is located in `experimental` (`benches/common` and `src/cost_runner` dirs)
- Aggregate `ContractCostType`, `WasmInsnType` and a new  **`ExperimentalCostType`** into top level `CostType`
Resolves #1030 
- Bring back `EdwardsPointCurve25519ScalarMul` as a experimental cost type and run variation histogram on it. 
[TODO or N/A]

Setup bench framework to run experiments

---

soroban-env-host/src/auth.rs
soroban-env-host/src/host_object.rs

Decorate error for nonce missing from the footprint.
Improving error diagnostics
N/A

Decorate error for nonce missing from the footprint.

---

soroban-env-host/src/e2e_invoke.rs
soroban-env-host/src/host/comparison.rs
soroban-env-host/src/host/declared_size.rs
soroban-env-host/src/host/metered_clone.rs
soroban-env-host/src/storage.rs

This comes out of some review on compare.rs: we were supporting a lot of LE types in the code that are not ever supposed to occur. It's better to treat the presence of those cases as internal errors than have dead code "supporting" them possibly incorrectly.
Also eliminates comparison of LEs altogether. They were only being compared because of older constraints on MeteredOrdMap wanting its value type to be comparable. That's not necessary for LEs (in the Storage map), only Vals (in HostMaps) in order to have Map be ordered itself (because Val must be ordered). Turns out we'd already relaxed the requirement on MeteredOrdMap's value type to not have to be comparable. So all the LE-ordering code was dead anyway, which is good because they were all being treated as calls to Ord on fixed size …

Remove bad LEs

---

soroban-env-host/src/host/comparison.rs
soroban-env-host/src/host/declared_size.rs

There were several cases in comparison.rs that did `.cmp` on values that really should be `.compare` to account for their (constant but nonzero) sizes. This change routes them all through `.compare` and adds fixed-size type macros to support them.

Add missing fixed-size metering in comparison.rs, clean up a bit

---

soroban-env-host/src/host.rs
soroban-env-host/src/host/mem_helper.rs

Tighten up metering for linear memory routines

---

soroban-env-common/src/convert.rs
soroban-env-common/src/error.rs
soroban-env-common/src/object.rs
soroban-env-common/src/val.rs
soroban-env-common/src/wrapper_macros.rs
soroban-env-host/benches/common/experimental/map_ops.rs
soroban-env-host/benches/common/experimental/vec_ops.rs
soroban-env-host/benches/common/util.rs
soroban-env-host/src/auth.rs
soroban-env-host/src/events/internal.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/comparison.rs
soroban-env-host/src/host/conversion.rs
soroban-env-host/src/host/data_helper.rs
soroban-env-host/src/host/frame.rs
soroban-env-host/src/host/metered_clone.rs
soroban-env-host/src/native_contract/testutils.rs
soroban-env-host/src/test/auth.rs
soroban-env-host/src/test/depth_limit.rs
soroban-env-host/src/test/num.rs
soroban-env-host/src/test/token.rs
soroban-env-host/src/test/util.rs
soroban-env-host/src/vm/dispatch.rs
soroban-synth-wasm/src/func_emitter.rs

Nothing deeply complicated in here, just a bunch of error plumbing, error code and check consolidation, double checks of internal logic, renames and comment gardening.
The most annoying parts of this PR are the bad errors we get from "anything going wrong during ScVal conversion" which is already noted as bug #1046 which I would love to fix but we probably don't have time; or at least last time I tried I gave up because it required too much SDK proc-macro hacking and error routing. Maybe I can try again sometime?

conversion.rs code review fixes

---

soroban-env-host/src/events/internal.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/declared_size.rs
soroban-env-host/src/host/metered_clone.rs

Fair amount of churn here:
- Removed several dead impls, cleaned up comments, added missing testcases, reordered stuff for consistency
- Reclassified and removed incorrectly-classified shallow types. This is fairly serious: we weren't counting the substructure cloning cost of much of the auth system as well as the wasm code of a contractcode entry, or the signers of an account entry.
One interesting part of this is that, as far as I can tell, everything in the events system doesn't use `metered_clone` anymore at all. I think this is good because it previously _errored_ when trying to `metered_clone` a diagnostic event, which is "just as observable" as `metered_cloning`-something-that-should-be-free would have been. Luckily it looks like we only "accumulate events", don't clone them, and …

Review fixes for declared_size and metered_clone

---

soroban-env-host/Cargo.toml
soroban-env-host/src/auth.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/conversion.rs
soroban-env-host/src/host/frame.rs

Gate recording auth behind the feature. It will also be automatically available for `testutils` builds (necessary for the SDK).
Recording auth is needed in non-test builds (for preflight), but not for validators. Thus we can compile it out for additional safety.
N/A

Gate recording auth behind the feature.

---

soroban-env-host/src/native_contract/token/balance.rs
soroban-env-host/src/native_contract/token/contract.rs
soroban-env-host/src/native_contract/token/test_token.rs
soroban-env-host/src/test/token.rs

Remove `spendable_balance` from SAC.
Resolves https://github.com/stellar/rs-soroban-env/issues/1118
As per update to SEP-41 (https://github.com/stellar/stellar-protocol/pull/1408) we decided to remove `spendable_balance` for the time being in order to reduce potential confusion.
N/A

Remove `spendable_balance` from SAC.

---

soroban-test-wasms/wasm-workspace/write_upgrade_bytes/src/lib.rs

Leave enough time for validators to inspect upgrades. It's important to note that the initial MAXIMUM_ENTRY_LIFETIME in core is 31 days, so that should be increased if this PR is accepted.

Extend upgrade contract from 30 to 60 days

---

soroban-env-host/src/host_object.rs

Fix #1135 (the new code here is not actually dynamically reachable but it's harmless to be extra-paranoid)

Clarify (and add redundant defensive code) in check_val_integrity

---

soroban-env-host/src/host/prng.rs

This allowed a contract to panic the host.

Fix fuzz-found panic in Prng::u64_in_inclusive_range

---

soroban-env-host/src/host/frame.rs

This used to be a panic but as of #1160 it's just an `InternalError`. Still, not something we want!

Fix fuzzer-found frame stack corruption in rollback if instance storage fails

---

soroban-env-host/src/host.rs
soroban-env-host/src/test.rs
soroban-env-host/src/test/finish.rs

Add fn to find out if Host can be finished.
So that the SDK can ask the Host if it has no more references left and it is able to be finished without calling try_finish which is destructive.
I plan to use this in:
- https://github.com/stellar/rs-soroban-sdk/pull/1137

Add fn to find out if Host can be finished

---

soroban-env-host/Cargo.toml
soroban-env-host/src/auth.rs
soroban-env-host/src/budget.rs
soroban-env-host/src/budget/dimension.rs
soroban-env-host/src/budget/util.rs
soroban-env-host/src/events/diagnostic.rs
soroban-env-host/src/events/internal.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/error.rs
soroban-env-host/src/host/frame.rs
soroban-env-host/src/test/budget_metering.rs
soroban-env-host/src/vm.rs

This does a few things @jayz22 and I discussed today:
1. Eliminates the second callback and the value-passing on the shadow and debug mode callbacks in favor of mutating a value outside the closure _when observation is required_. This is not necessarily better, just a little more awkward / less likely to be done accidentally without thinking about it.
2. Removes all convenience accessors for the debug flag, again just to make it harder to accidentally observe.
3. Feature-gates DebugInfo on testutils, so it's never live in production. Note that DebugInfo is _not_ the diagnostic event buffer, it's a snapshot of the buffer along with a (native) backtrace attached to errors that get printed to console in a panic catch, it only makes sense for testing and by eliminating it here we can actually …

tighten up handling of debug mode

---

soroban-env-common/src/option.rs

Remove unnecessary copy of value.
Does not appear to be necessary.

Remove unnecessary copy of value

---

.github/CODEOWNERS

Add @dmkozh as code owner of `soroban-env-host`.
So that @dmkozh is mentioned on any PRs that modify the host, in the same way that @graydon and @sisuresh are.

Add @dmkozh as code owner of soroban-env-host

---

.github/workflows/rust.yml

Don't block merges on rust-analyzer compat check.
Lately it's taking a long time to run, longer than other jobs in the workflows.
It's been more than 6 months I think since we broke this compat check. We might not need it anymore. We just don't seem to be stumbling upon limitations in rust-analyzer, we might mean the things we were stumbling on in the past have been fixed. We could remove it. Simply stopping it from blocking merges is a step towards doing that.
Related:
- https://github.com/stellar/rs-soroban-sdk/pull/1151

Don't block merges on rust-analyzer compat check

---

soroban-env-host/src/lib.rs

Pub ContractInvocationEvent.
The contract invocation hook function exposes the type to importers, but because it isn't public they can't reference it to do things like matching.

Pub ContractInvocationEvent

---

soroban-env-host/src/host.rs
soroban-env-host/src/host/frame.rs

Pass ref to host to contract invocation hook.
So that hook implementations have access to the host without needing to hold a reference to the host via some other means.
This is the pattern used on other hooks in the Host.

Pass ref to host to contract invocation hook

---

soroban-env-host/src/host.rs
soroban-env-host/src/host/frame.rs

Trigger top contract invocation finish hook after storing the auth manager.
So that hook implementations can access the auth state that occurred during the run.
Intended to be merged to `main` after:
- #1230

Fix top contract invocation hook and auth interaction

---

soroban-env-host/src/budget/limits.rs
soroban-env-host/src/host/metered_xdr.rs
soroban-env-host/src/test/depth_limit.rs
soroban-env-host/src/vm.rs

- Use the input-based limit for the de-serialization (we always know the buffer size before decoding it)
- Increase the default 'width' limit to 32MiB - is is only used for serialization now. Serialization is protected by the budget metering, so there is no need to be too restrictive with the hard limit.
Improve XDR safety/usability
N/A

XDR limits updates

---

soroban-env-common/src/arbitrary.rs

Add size_hint methods to Arbitrary impls.
It should make fuzzers more effective at producing arbitrary input, particularly in cases where these types are included in structs or collections.
Note that the `impl Arbitrary for Symbol` doesn't need an implementation - the default `(0, None)` is appropriate.
Closes https://github.com/stellar/rs-soroban-sdk/issues/1147

Add size_hint methods to Arbitrary impls

---

Cargo.toml
Makefile
soroban-bench-utils/Cargo.toml
soroban-builtin-sdk-macros/Cargo.toml
soroban-env-common/Cargo.toml
soroban-env-host/Cargo.toml
soroban-env-host/fuzz/Cargo.lock
soroban-env-host/fuzz/Cargo.toml
soroban-env-macros/Cargo.toml
soroban-synth-wasm/Cargo.toml
soroban-test-wasms/wasm-workspace/Cargo.toml

This does the env side of #1222 -- there are still core-side things to do but this is a step.
No packages are changed in the main lockfile here, just the one in the fuzzer sub-workspace which was out of sync.

Cargo version pinning

---

soroban-env-host/src/budget/limits.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/ledger_info_helper.rs
soroban-env-host/src/storage.rs

Resolves #1141 
Several places benefit from changing `saturating_` to `checked_` math:
- `saturating_add(_mul)` on u32, saturation would be within possibility
- Some `saturating_sub` saturation would mean actual error, e.g index out of bound
In both cases, changing to `checked_` version means overflow errors are caught sooner. 
[TODO or N/A]

Tighten up `saturating_` math checks

---

soroban-env-host/src/host/frame.rs

Mostly minor stuff:
- Change errors that are really logic errors into InternalError
- Notice and error in a case a callback overwrites the local PRNG while it's being established (we don't do this anywhere but in the future someone might accidentally)
- Factor out some common code
- Rewrite stuff for legibility (especially the reentry-prevention code which was hard to follow)
- Fix a couple comments and imports
No functional (or at least observable) change.

Frame code review

---

soroban-env-host/benches/common/measure.rs
soroban-env-host/src/budget.rs
soroban-env-host/src/budget/dimension.rs
soroban-env-host/src/budget/model.rs
soroban-env-host/src/cost_runner/experimental/ed25519_scalar_mut.rs
soroban-env-host/src/cost_runner/experimental/read_xdr.rs
soroban-env-host/src/cost_runner/runner.rs
soroban-env-host/src/test/budget_metering.rs
soroban-env-host/src/test/bytes.rs
soroban-env-host/src/test/map.rs
soroban-env-host/src/test/vec.rs

Improve the budget tracker. With a bit code reorg and tightening.
The `BudgetTracker` used to contain the `(iterations, inputs)` pair for each cost type. This PR adds to it the `cpu`, `mem` costs. 
`get_tracker` can return granular costs which can be filtered/aggregated downstream for better metrics. 
[TODO or N/A]

Improve budget tracker

---

soroban-env-common/src/env.rs
soroban-env-common/src/string.rs
soroban-env-guest/src/guest.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/contract.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/metadata.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/error.rs
soroban-env-host/src/test/str.rs

Change `string_new_from_slice` to use `&[u8]` instead of `&str`.
Resolves https://github.com/stellar/rs-soroban-env/issues/1188
`String` host type doesn't provide encoding guarantees and usually is encoded is `&[u8]`; this function is inconsistent with the rest of the API.
N/A

Change `string_new_from_slice` to use `&[u8]` instead of `&str`.

---

soroban-env-host/src/builtin_contracts/stellar_asset_contract/balance.rs

The SAC uses the `AuthorizedToMaintainLiabilitiesFlag` to deauthorize a trustline. If a trustline is completely deauthorized (`AuthorizedFlag` and `AuthorizedToMaintainLiabilitiesFlag` are both not set) and you call the deauthorize function from the SAC on it, the SAC will set `AuthorizedToMaintainLiabilitiesFlag`. This PR makes that scenario (as well as authorizing an authorized trustline) a noop for the auth flag state.

Noop auth fix

---

soroban-env-host/Cargo.toml
soroban-env-host/benches/common/cost_types/wasm_insn_exec.rs
soroban-env-host/src/test/hostile.rs
soroban-env-host/src/test/post_mvp.rs
soroban-env-host/src/testutils.rs
soroban-synth-wasm/Cargo.toml
soroban-synth-wasm/src/func_emitter.rs
soroban-synth-wasm/src/mod_emitter.rs
soroban-synth-wasm/src/test.rs

Test bad WASMs

---

soroban-env-host/src/e2e_invoke.rs
soroban-env-host/src/events/diagnostic.rs
soroban-env-host/src/events/internal.rs
soroban-env-host/src/events/mod.rs
soroban-env-host/src/events/system_events.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/data_helper.rs
soroban-env-host/src/host/error.rs
soroban-env-host/src/host/mem_helper.rs
soroban-env-host/src/host/metered_map.rs
soroban-env-host/src/host/metered_vector.rs
soroban-env-host/src/host/num.rs
soroban-env-host/src/host_object.rs
soroban-env-host/src/vm.rs

This covers the remainder of my code review on soroban.
Fixes #1225

Remaining host code review

---

.cargo/config.toml
Cargo.lock
soroban-env-host/Cargo.toml
soroban-env-host/benches/common/cost_types/compute_ecdsa_secp256k1_sig.rs
soroban-env-host/benches/common/cost_types/compute_keccak256_hash.rs
soroban-env-host/benches/common/cost_types/compute_sha256_hash.rs
soroban-env-host/benches/common/cost_types/host_mem_alloc.rs
soroban-env-host/benches/common/cost_types/host_mem_cmp.rs
soroban-env-host/benches/common/cost_types/host_mem_cpy.rs
soroban-env-host/benches/common/cost_types/prng.rs
soroban-env-host/benches/common/cost_types/recover_ecdsa_secp256k1_key.rs
soroban-env-host/benches/common/cost_types/val_deser.rs
soroban-env-host/benches/common/cost_types/val_ser.rs
soroban-env-host/benches/common/cost_types/verify_ed25519_sig.rs
soroban-env-host/benches/common/cost_types/visit_object.rs
soroban-env-host/benches/common/cost_types/vm_ops.rs
soroban-env-host/benches/common/measure.rs
soroban-env-host/benches/common/mod.rs
soroban-env-host/benches/common/modelfit.rs
soroban-env-host/benches/variation_histograms.rs
soroban-env-host/benches/worst_case_linear_models.rs
soroban-env-host/src/budget.rs
soroban-env-host/src/budget/model.rs

This PR was originated from the fact that previously the `VarDeser` cost's constant term was unrealistically high.  
It improves the numerical approach towards model generation by constraining it to the smallest input in the range. 
Thus it avoids fitting a model that tries to produce a marginally better fitness at the expense of lower-range accuracy. 
It also removes the dependency of the `HostCostMeasurement`'s input size on the linear parameter's scale factor (`COST_MODEL_LIN_TERM_SCALE_BITS`), which previously put a numerical constrain on the smallest input size and minimal gaps.
[raw calibration outputs](https://github.com/stellar/rs-soroban-env/files/13621533/output_x86_dec_8.txt)
[TODO or …

Improve cost model fitting for better lower-range accuracy

---

Cargo.lock
soroban-env-host/Cargo.toml
soroban-env-host/benches/common/cost_types/wasm_insn_exec.rs
soroban-env-host/src/budget/wasmi_helper.rs
soroban-env-host/src/test/hostile.rs
soroban-env-host/src/testutils.rs
soroban-synth-wasm/src/func_emitter.rs
soroban-synth-wasm/src/mod_emitter.rs
soroban-synth-wasm/src/test.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/1145
Add rest of the bad wasm cases:
- SIMD
- invalid const-expressions in
- global
- active elements table
- active data segment mode
- very large sections
- tables
- types
[TODO or N/A]

Bad wasm tests

---

soroban-env-host/Cargo.toml

Resolve https://github.com/stellar/rs-soroban-env/issues/1294
Verified that the files are now excluded using `cargo package --list.`

Exclude observations

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml

Update stellar-xdr to v20.0.2
Include the changes in stellar-xdr in a soroban-env release. The changes will have no protocol impact:
https://github.com/stellar/rs-stellar-xdr/compare/v20.0.0...v20.0.2

Update stellar-xdr to v20.0.2

---

.github/workflows/rust.yml

Rust 1.75 emits some new dwarf debuginfo that cackle 0.6.0 didn't understand. This was [fixed in cackle](https://github.com/cackle-rs/cackle/commit/0d1a38e4005ccc54a2c7e39efb7f8d7061545f74) a while ago we just have a pinned dependency. This PR updates that pin.

Bump cackle-action to 0.7.0 to support debuginfo changes in rust 1.75

---

soroban-env-host/tests/ed25519_edge_cases.rs

This contains some new test vectors for testing dalek against some known edge cases of ed25519. I'm about to file a corresponding stellar-core change that runs the same test vectors through libsodium (they both behave the same).

Add test vectors for ed25519 edge cases

---

soroban-env-host/observations/test__event__test_observation_does_not_emit_diagnostic_events_from_failed_borrows.json
soroban-env-host/src/host/trace.rs
soroban-env-host/src/test/event.rs

The recently-added tracing machinery accidentally emits "internal error" diagnostic events if a trace-induced borrow fails. This PR fixes it.

Trace should not emit diagnostic errors

---

soroban-env-host/src/events/mod.rs

What it says on the label.
Fixes #1049

Use strkeys for contract IDs and addresses in diagnostic events.

---

soroban-env-host/observations/test__hostile__test_extern_ref_not_allowed.json
soroban-env-host/observations/test__hostile__test_large_number_of_tables.json
soroban-env-host/src/budget.rs
soroban-env-host/src/budget/util.rs
soroban-env-host/src/budget/wasmi_helper.rs
soroban-env-host/src/test/hostile.rs
soroban-env-host/src/testutils.rs
soroban-env-host/src/vm.rs

Disable wasmi `reference_types`and make all wasmi feature selections explicit.
Also did a pass-by clean up on the fuel configs code. 
`bulk_memory` and `reference_types` are both post-MVP features.
We use 1 extensively for object init/copy between host and guest. 
We do not use 2 at all. We are not using `ExternRef` and we are limiting table count to 1 (via resource limiter).
[TODO or N/A]

Turn off `wasm_reference_types` in Wasmi

---

.github/workflows/rust.yml
soroban-simulation/Cargo.toml

Enable publish of soroban-simulation crate
It is depended on by the soroban-rpc and should have been included in the v20.2.0 release, but appears we forgot to set it as publishable.

Enable publish of soroban-simulation crate

---

soroban-env-host/Cargo.toml

This is a small followup/cleanup after https://github.com/stellar/rs-soroban-env/pull/1354. Updated comments and exclude some features from the generated docs.
Cleanup
N/A

Cleanup Cargo.toml for `unstable-next-api` feature

---

soroban-simulation/src/network_config.rs

- Use `&impl SnapshotSourceWithArchive` in `load_from_snapshot`. This is not very pretty semantically, but there is no clean way for storage to implement archived entry filtering without accessing the config and I really want to encapsulate the config-related logic in `NetworkConfig` struct. The alternative would be for `SnapshotSource` implementer to either load the state expiration config before building the config, or to not follow the interface contract of `SnapshotSource` to not ever return expired entries.
- Use `&self` in `fill_config_fields_in_ledger_info`
Issue fixes
N/A

Small fixes in soroban-simulation

---

soroban-simulation/src/simulation.rs
soroban-simulation/src/snapshot_source.rs
soroban-simulation/src/test/simulation.rs
soroban-simulation/src/test/snapshot_source.rs

Emulate account entry extensions in simulation.
This also adds a general mechanism for modifying any ledger entries retrieved from the snapshot.
Improve simulation accuracy.
Fixes https://github.com/stellar/rs-soroban-env/issues/1357
N/A

Emulate account entry extensions in simulation.

---

soroban-env-host/src/host/declared_size.rs
soroban-env-host/src/test/hostile.rs
soroban-env-host/src/vm.rs
soroban-env-host/src/vm/module_cache.rs
soroban-env-host/src/vm/parsed_module.rs

Charge for BTreeSet creation in the `ParsedModule`/`ModueCache`
The BTreeSet was the right structure to use, but its cost was not charged for by the budget. 
Here we account for the cost of its creation (memory allocation, copy).
Using `MeteredMap` would be more correct from metering perspective, which accounts for all look-ups and insertions. However, it is too inconvenient to use (every insertion creates a new map), and the extra lookup/insertion costs should be limited to worth the churn.

Charge for BTreeSet

---

soroban-simulation/src/network_config.rs
soroban-simulation/src/test/network_config.rs

Pass bucket list size to simulation as a side input.
While it would be nice to encapsulate the computation logic based purely on the ledger state, we don't currently emit the necessary meta to track the respective config entry changes.
N/A

Pass bucket list size to simulation as a side input.

---

Cargo.lock
Cargo.toml
soroban-env-host/src/e2e_invoke.rs
soroban-env-host/src/storage.rs
soroban-env-host/src/testutils.rs

This is a followup to https://github.com/stellar/rs-soroban-env/pull/1384 that ungates the `unstable-next-api` feature code (and deletes the previous variants) and sets the package version to 21.0.0

Package version 21

---

soroban-simulation/src/network_config.rs
soroban-simulation/src/test/network_config.rs

Extend cost params in simulation in order to match the hardcoded value.
Env expects cost params to have the same size as defined in XDR, even if protocol doesn't use these params yet. This is a temporary workaround until https://github.com/stellar/rs-soroban-env/issues/1388 is resolved.
N/A

Extend cost params in simulation in order to match the hardcoded value.

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml

Use the released 21.0.0 XDR.
Preparing for 21.0.0 release
N/A

Use the released 21.0.0 XDR.

---

soroban-env-host/observations/20/test_v_new_call_nonexistent_wasm_call.json
soroban-env-host/observations/20/test_v_new_call_runtime_deleted_wasm_call.json
soroban-env-host/observations/20/test_v_new_rewrite_call_fail.json
soroban-env-host/observations/21/test_v_new_call_nonexistent_wasm_call.json
soroban-env-host/observations/21/test_v_new_call_runtime_deleted_wasm_call.json
soroban-env-host/observations/21/test_v_new_rewrite_call_fail.json
soroban-env-host/src/auth.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/balance.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/data_helper.rs
soroban-env-host/src/host/error.rs
soroban-env-host/src/host/frame.rs
soroban-env-host/src/host/lifecycle.rs
soroban-env-host/src/storage.rs
soroban-env-host/src/test/auth.rs
soroban-env-host/src/test/lifecycle.rs
soroban-env-host/src/test/lifetime_extension.rs
soroban-env-host/src/test/stellar_asset_contract.rs

Improved TTL testing UX and cleaned up storage diagnostics.
Both improvements rely on passing host into storage methods. This also allows us to use the ledger info and to encapsulate detailed diagnostic errors in the storage module.  We have to still keep the old storage methods around. There are a few users of storage getters, which probably don't have to use it, but the clean up will have some time and can only be performed in v22 due to semver.
There is a subtle change in observations because we now only allocate a new object in diagnostic mode (charged to shadow budget). However, this shouldn't cause divergence (because this version of env won't run in p20) and is highly unlikely to affect replay of p20 with the new env. If necessary, we can still emulate the p20 behavior.
The TTL …

Improved TTL testing UX and cleaned up storage diagnostics.

---

soroban-env-common/env.json
soroban-env-host/src/storage.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/1329
[TODO or N/A]

Update docs to clarify `extend_ttl` return conditions

---

Cargo.lock
soroban-env-common/Cargo.toml
soroban-env-host/Cargo.toml

This update is required for https://github.com/stellar/stellar-core/pull/4328 to go through

Bump tracy-client to 0.16.4 and tracy-client-sys to 0.22.2 (for tracy v0.10)

---

.github/workflows/rust.yml
deny.toml
soroban-env-common/src/tuple.rs
soroban-env-host/Cargo.toml

Allow using higher versions of dalek in env.
Unblock the deps from picking up new versions of dalek, specifically the ones with vulnerability fixes. We don't strictly bump the version in order to make sure we don't break the Core build.
N/A

Allow using higher versions of dalek in env.

---

Cargo.lock
soroban-bench-utils/Cargo.toml
soroban-env-common/Cargo.toml
soroban-env-host/Cargo.toml
soroban-env-host/src/host/crypto.rs

This bumps the tracy-client crate to 0.17, so that we can access the `delayed-init` feature (it's not present in 0.16.4 but necessary to use with core). Previously we were patching this dep entirely with a local vendored build of tracy in core, so this potentially moves us closer to upstream (if it work).

Bump tracy-client to 0.17 to expose delayed-init feature

---

soroban-env-host/src/test/e2e_tests.rs

Add e2e tests to cover unsupported Wasm upload failure.
While we do cover this at a lower level, it's nice to have an e2e test that makes sure that VM configuration is correct. We also do have e2e tests for completely malformed Wasm failures, this scenario is different because Wasm is not malformed.
Improving test coverage
N/A

Add e2e tests to cover unsupported Wasm upload failure.

---

soroban-env-host/src/events/mod.rs

Resolves https://github.com/stellar/rs-soroban-env/issues/1463
Before 
```
Event log (newest first):
0: [Diagnostic Event] contract:CAXDPD4A5ANAASQ2U74RBW7ULGB3TS5SGSAFYPN6O2R2IJKGEX22SWUS, topics:[error, Error(Contract, https://github.com/stellar/rs-soroban-env/pull/8)], data:["negative amount is not allowed", -1]
1: [Diagnostic Event] topics:[fn_call, Bytes(2e378f80e81a004a1aa7f910dbf45983b9cbb234805c3dbe76a3a4254625f5a9), mint], data:[GD4YHMIZ7IGW7E4XJ4TXIJPLJU255JXPM2PKTV6H4PA4N5RTM6T2R73D, -1]
2: [Diagnostic Event] contract:CAXDPD4A5ANAASQ2U74RBW7ULGB3TS5SGSAFYPN6O2R2IJKGEX22SWUS, topics:[fn_return, init_asset], data:Void
3: [Diagnostic Event] topics:[fn_call, Bytes(2e378f80e81a004a1aa7f910dbf45983b9cbb234805c3dbe76a3a4254625f5a9), init_asset], …
```

Format contract id in fn_call event topic

---

deny.toml

Replace cargo-deny `skip-tree` with explicit `skip`s for each dependency we wish to allow duplicates.
The `skip-tree` obfuscates the dependencies that we're allowing to be duplicated, and even seems to hide some dependencies being duplicated that don't seem to be part of the soroban-wasmi dependency graph that we depend. This may be due to a bug, or possibly the dep is in the dev dependencies of soroban-wasmi, or some feature that we don't use.
I became aware of this issue because I noticed that in #1456 the Cargo.lock file gained a duplicate dependency on the `syn` crate, having already a dependency on version `2.0.39` and gaining a dependency on version `1.0.109`. This is fine and not a problem in and of itself – we can't eradicate all duplicates – except that the `deny.toml` file …

Replace cargo-deny skip-tree with explicit skips

---

soroban-env-host/src/host/metered_map.rs
soroban-env-host/src/host/metered_vector.rs

Ported the implementation of binary search from Rust <=1.81 to Soroban env.
This is necessary for 2 reasons:
- Fix the immediate issue of CI failing due to observation divergence in Rust 1.82 caused by the binary search implementation change
- Protect ourselves from the similar issues in the future - we were effectively observing the stdlib implementation and that's incorrect and risky in the long term.
N/A

Ported the implementation of binary search from Rust <=1.81 to Soroban

---

soroban-env-common/src/convert.rs
soroban-env-common/src/option.rs
soroban-env-common/src/tuple.rs
soroban-env-common/src/val.rs
soroban-env-common/src/wrapper_macros.rs

Fill gaps in ref conversions to Val.
Needed for:
- https://github.com/stellar/rs-soroban-sdk/pull/1382

Fill gaps in ref conversions to Val

---

.github/workflows/rust.yml

Disable semver checks temporarily.
The check is broken due to `arbitrary` crate update (https://github.com/rust-fuzz/arbitrary/issues/203).
N/A

Temporarily disable semver checks.

---

soroban-env-host/src/auth.rs
soroban-env-host/src/e2e_testutils.rs
soroban-env-host/src/test/e2e_tests.rs

Emulate access to custom account instance and Wasm in recording auth.
The change gracefully handles failures (e.g. allows for the instance not being present) in order to not spam diagnostics in unit tests that don't care about the footprint (which makes up for majority of the unit tests).
Better emulate the authorization behavior (in some edge cases this might allow for single-pass simulation of custom accounts).
Resolves https://github.com/stellar/rs-soroban-env/issues/1443
In theory, we could also try calling `__check_auth` on the contract (if possible), but that will likely produce confusing diagnostics for most of the contracts (e.g. signature verification errors).

Emulate access to custom account instance and Wasm in recording auth.

---

.github/workflows/rust.yml

Re-enable semver-checks.
They should be unstuck now.
N/A

Re-enable semver-checks.

---

soroban-env-host/src/budget/dimension.rs
soroban-env-host/src/budget/util.rs
soroban-env-host/src/events/internal.rs
soroban-env-host/src/fees.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/frame.rs
soroban-env-host/src/host/invocation_metering.rs
soroban-env-host/src/host/lifecycle.rs
soroban-env-host/src/storage.rs
soroban-env-host/src/test/auth.rs
soroban-env-host/src/testutils.rs

This is an opt-in feature that will reset the budget and take a storage snapshot for every 'logical' invocation (such as `call` or a lifecycle operation). Then when the invocation is done we use the snapshot and current budget to produce the estimate for the resources consumed by the invocation (budget-related, IO-related and rent bumps).
This also provides a rough estimation for the respective fee breakdown given a fee config.
Make unit tests more useful for rough performance evaluation. This is the initial env-side implementation for https://github.com/stellar/rs-soroban-sdk/issues/1319
Some of the resources are tricky to model. Specifically, this omits:
- transaction size
- return value size
- some XDR roundtrips that always happen for production scenarios
These shouldn't be too …

Add a test-only mechanism for metering most of the relevant resources per-invocation

---

soroban-env-host/src/host.rs
soroban-env-host/src/lib.rs

Expose structs used for invocation metering.
These are meant to be public.
N/A

Expose structs used for invocation metering.

---

soroban-env-host/src/e2e_invoke.rs
soroban-env-host/src/test/e2e_tests.rs
soroban-simulation/Cargo.toml
soroban-simulation/src/simulation.rs
soroban-simulation/src/test/simulation.rs

Allow passing the setting for non-root auth to the simulation.
This is unfortunately a breaking change and thus it needs to be guarded by unstable-next-api feature.
This allows for more control over the simulation logic - while the default is sufficient 99% of the time, there is still 1% of the cases where non-root auth should be allowed.
N/A

Allow passing the setting for non-root auth to the simulation.

---

soroban-env-host/src/auth.rs
soroban-env-host/src/host/invocation_metering.rs

Add invocation resource metering to check auth testutil.
Also harden the unit tests a bit to ensure that budget matches the CPU/memory we report in invocation resources and add a test case for a failed call.
Fix for https://github.com/stellar/rs-soroban-sdk/issues/1421, still needs to be picked up by the SDK.
N/A

Add invocation resource metering to check auth testutil.

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml

Bump XDR for env.
This currently only affects the vnext of XDR.
Preparing for Core changes.
N/A

Bump XDR for env.

---

soroban-env-host/src/test/e2e_tests.rs

Tighten the budget estimations in e2e tests.
There was a small bug in the module cache construction - we didn't consider the proper version of the code entry when building the module cache to pass to the enforcing mode. This fix allows us to bring the discrepancy between the recording and enforcing modes back to 0.02.
Test fixes
N/A

Tighten the budget estimations in e2e tests.

---

soroban-env-host/src/e2e_invoke.rs
soroban-env-host/src/test/e2e_tests.rs
soroban-simulation/src/test/simulation.rs

Remove `unstable-next-api` feature guards.
We don't need these anymore as host has already been switched to v23.
N/A

Remove `unstable-next-api` feature guards.

---

soroban-env-common/src/env.rs
soroban-env-guest/src/guest.rs
soroban-env-host/src/host.rs

Remove the check_same_env function from the EnvBase trait and move it into the Host impl.
Functions in the EnvBase are implemented by Host and Guest. The check_same_env function is only used by the soroban-sdk. In https://github.com/stellar/rs-soroban-sdk/pull/1436 the soroban-sdk is no longer going to be calling the function on the Guest, and only calling it directly on the Host. So there's no longer a need for it to be part of this trait/interface.

Remove check_same_env from EnvBase trait

---

.github/workflows/rust.yml
Cargo.toml
Makefile
rust-toolchain.toml
soroban-env-host/Cargo.toml
soroban-test-wasms/wasm-workspace/Cargo.toml
soroban-test-wasms/wasm-workspace/Makefile

Part of wrapping up https://github.com/stellar/rs-soroban-sdk/issues/1428 -- just supporting wasm32v1-none

switch to wasm32v1-none for contract wasm target

---

soroban-env-host/src/bin/main.rs
soroban-env-host/src/e2e_invoke.rs
soroban-env-host/src/host/declared_size.rs
soroban-env-host/src/host/metered_clone.rs
soroban-env-host/src/test/e2e_tests.rs
soroban-simulation/src/test/simulation.rs

Properly handle auto-restored entries in e2e_invoke.
There are two requirements for auto-restored entries:
- If entry is not removed, it must be extended by at least min persistent TTL (notably, this should be reflected in the host function effects)
- The entry is considered to have not existed for the purpose of rent (i.e. it's initial size and live_until_ledger are 0)
Both requirements can be easily fulfilled in get_ledger_changes, given that we have the restored_entry_ids passed from the transaction.
Also added a couple tests that cover that.
CAP-66 implementation
N/A

Properly handle auto-restored entries in e2e_invoke.

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml

Updates the stellar-xdr dependency to the latest commit from the default branch (323f7de1cc2b956dde2de9da8622a261baf2977e).
Keep the repository in sync with the latest stellar-xdr changes.

Update stellar-xdr dependency to latest commit

---

Cargo.lock
Cargo.toml
soroban-env-host/Cargo.toml

Update XDR to v23.0.0-rc.1
Preparing for v23.0.0-rc.1 release
N/A

Update XDR to v23.0.0-rc.1

---

soroban-env-host/src/host.rs
soroban-env-host/src/test/host.rs

Rename the host comparison method from check_same_env to is_same, changing it to return a boolean instead of a Result.
The new name better reflects the method's purpose of being used by the SDK to compare two Hosts and determine if they in fact are the same underlying host implementation. The check function returns a result with the host assuming that there is in fact an error, whilst the is function returns a bool, merely providing information to the SDK so that the SDK can then decide in the context of its use whether there is an error or a change in behaviour is required.
Close #1554 
Related:
- https://github.com/stellar/rs-soroban-sdk/pull/1467#discussion_r2094183786

Rename Host::check_same_env to Host::is_same

---

soroban-env-host/src/auth.rs
soroban-env-host/src/builtin_contracts/stellar_asset_contract/balance.rs
soroban-env-host/src/e2e_invoke.rs
soroban-env-host/src/host.rs
soroban-env-host/src/host/data_helper.rs
soroban-env-host/src/host/frame.rs
soroban-env-host/src/host/invocation_metering.rs
soroban-env-host/src/host/lifecycle.rs
soroban-env-host/src/storage.rs
soroban-env-host/src/test/auth.rs
soroban-env-host/src/test/lifecycle.rs
soroban-env-host/src/test/stellar_asset_contract.rs
soroban-env-host/src/testutils.rs

Add test utilities to compensate hiding the storage interface.
Also do a small passing-by cleanup for the storage function names.
There generally should not be a need to expose the Storage implementation to the env users; the interface is pretty complex and we want to be able to change it (as we did e.g. for the error handling). The test utilities make sure the Storage remains mostly encapsulated in host, while SDK gets the necessary tools to read/write the arbitrary ledger entries (which is mostly useful for SAC setup - maybe eventually this should be moved to host as well, as this is protocol level logic).
N/A

Add test utilities to compensate hiding the storage interface.

---

soroban-env-host/src/budget.rs
soroban-simulation/src/network_config.rs

Scale shadow CPU limit in simulation 10x, shadow memory limit 2x.
This picks up a commit released in the 22.1.4 release of env.
Shadow limit has never been meant as a hard limit that would cause the simulation to fail. However, since module cache emulation is now off-loaded to the shadow budget, it became relatively easy to hit the shadow budget limit by doing repeated calls to the same contract (which is now cheap for the actual 'enforcing' mode).
Eventually this may become a setting, but that would be nicer to do with a breaking change in the simulation API in order to not duplicate the interfaces.
N/A

Scale shadow CPU limit in simulation 10x, shadow memory limit 2x.

---

soroban-env-host/src/host/error.rs

Remove the limit from the event debug info implementation.
Resolves https://github.com/stellar/rs-soroban-env/issues/1288
It doesn't seem like this provides any tangible safety benefits, as events are already charged to budget (or shadow budget) and Debug is only used for tests or verbose logging in Core. If a consumer is concerned about the amount of data output, it would make more sense to limit to overall size of the output buffer.
N/A

Remove the limit from the event debug info implementation.

---

soroban-env-host/src/fees.rs
soroban-env-host/tests/fees.rs
soroban-simulation/src/test/simulation.rs
soroban-simulation/src/test/snapshot_source.rs

disk_read_entries should already be set to `numClassic(readOnly) + numClassic(readWrite) + sizeof(archivedSorobanEntries)` when passed in, so adding readWrite.size() is incorrect.

Stop adding write entry count to disk read entry count

---

soroban-env-host/src/bin/main.rs
soroban-env-host/src/e2e_invoke.rs
soroban-env-host/src/test/e2e_tests.rs
soroban-simulation/src/test/simulation.rs

Pass actual restored entry ids into invoke_host_function.
Previously we've passed the full resource extension into it, which might result in treating an already restored entry as being restored again (and charging the respective rent fee for it).
Bug fix.
N/A

Pass actual restored entry ids into invoke_host_function.

---

Cargo.toml

This just adds `debug=true` to the release profile. I am not 100% sure we want to do this, but I think we probably do.
The default build of stellar-core is already opt-with-debug and this is typically what both devs and I think even ops folks want: the ability to run at full speed but also place breakpoints in a few places and get a not-terrible backtrace in a pinch.
So this change just sets soroban's default to the same, such that when stellar-core builds a soroban submodule with release profile, it gets the same opt-with-debug experience.
For a full non-opt-with-debug build, the `dev` profile already works and will continue to work. This is just related to the release profile.
The counterargument to landing this might be like "we want the release binary to be small" or "we want it to …

Turn on debug=true for release profile

---

soroban-env-host/src/host/trace.rs

Part of https://github.com/stellar/rs-soroban-env/issues/1578 -- diagnostic events were being eaten in trace mode due to exhaustion of shadow budget.

Bump TRACE_STATE_SHADOW_*_LIMIT_FACTORs by 10x to avoid exhaustion

---

soroban-env-host/src/host/frame.rs
soroban-env-host/src/storage.rs
soroban-env-host/src/test/e2e_tests.rs
soroban-simulation/src/test/simulation.rs

Fix simulation for auto-restored contract code.
When a contract code entry is auto-restored, it will likely miss the module cache (if it's been in the hot archive), so we should charge the recompilation to the budget (in the same way as we already do for the entry that has been just created via upload).
Improving simulation accuracy.
N/A

Fix simulation for auto-restored contract code.

---

soroban-env-host/src/host.rs
soroban-env-host/src/host/error.rs
soroban-env-host/src/host/trace.rs
soroban-env-host/src/storage.rs

Currently this produces no observation diffs, because apparently we only call debug mode within host functions, and we don't trace host functions calling another host functions. This may change soon with the invocation metering changes.
This also adds a test-only check asserting that debug mode does not create new objects. Since we do create new objects when producing errors, I've also added a way to explicitly bypass that check.
Provide a clean way to write debug mode code that doesn't create bogus observation diffs.
N/A

Disable tracing for the code executed in debug mode.

---

soroban-env-host/src/auth.rs

Improve the error message for bad invoker auth.
Frequently the users would forget about authorize_as_current_contract for non-direct invokers, or have incorrect arguments. When non-root auth is disabled (which is the default), this ends up with the blanket 'non-root auth' error, which is confusing and makes it appear as if the invoker contract should be made into custom account and have `require_auth` called for it at the top level. With this change we will return a different error if the contract is a non-direct invoker.
Note, that in the scenario where non-root auth is allowed, we will record a detached auth entry for the offending contract. This is expected and we can't do much about that - since the mode is meant for the advanced users, the hope is that they will notice the unexpected …

Improve the error message for bad invoker auth.

---

.github/workflows/rust.yml
Cargo.lock
soroban-env-host/Cargo.toml
soroban-env-host/src/auth.rs
soroban-env-host/src/host/frame.rs
soroban-env-host/src/test/e2e_tests.rs
soroban-simulation/src/test/simulation.rs

That reflects the actual on-chain behavior of the module cache, which always unconditionally charges v0 VM instantiation costs.
Curiously, this change causes the recording and enforcing mode instruction counts to go *down* in the e2e tests, which is visible in the PR. However, the intention of the change is to actually fix simulation for the rare cases where v0 cost are higher than v1 cost. 
Note, that in case of the enforcing mode the change happens due to a fix that replicates the inter-ledger module cache logic in the test setup. Specifically, we always unconditionally charge v0 instantiation cost when instantiating a module from the cache, while previously the test setup usually used v1 instantiation cost. The simulation change replicates that behavior in the recording mode. 
I've …

Use v0 instantiation VM costs for cached Wasms.
